### ISSUE TITLE
Modal message "Initializing Language Server for ts" not disappearing and blocking the ui

### ISSUE THREAD

**Issue by hilumcool** [codenvy/codenvy#2155] opened 2017-05-02 21:14 UTC
Every now and then a after initializing the workspace and showing the last open files, the small modal message 

_"Initializing Language Server for ts"_

doesn't disappear and therefore blocks the ui.

**Reproduction Steps:**
- none (random effect)

**Special observations:**
- No such problems before 5.9.x (BUT ts language server wasn't started in earlier versions due to a bug, which was corrected in 5.9.x - if I remember right.
- Maybe issues #2154 and #2146 are directing towards the same cause? I don't have any Internet connection problems, and my bandwidth is large enough, though.
- Remedy: Reloading the workspace (with 'reload page' in the browser) always puts away the modal message.

**Codenvy version:** : 5.9.1 (SaaS, codenvy.io)

**OS and version:** Chrome OS, 58.0.3029.89 beta (client)

**Comment by 20avva** [comment] 2017-05-02 23:58
Similar incident happened to me in #1983 but this was with the py language server. That was resolved by installing pip3 through apt-get. Not sure what to do here...

**Comment by eivantsov** [comment] 2017-05-03 13:58
I just tried it with a node stack and it worked for me. What stack did you use for this language server?

**Comment by hilumcool** [comment] 2017-05-03 20:22
I took 
- your codenvy-legacy -> node (latest) dockerfile (https://github.com/codenvy-legacy/dockerfiles/blob/master/node/latest/Dockerfile), 
- looked at your instructions for Angular 2 and Che (https://eclipse.org/che/docs/tutorials/angular2/index.html) and 
- tried to mix and adapt everything in order to being able to use the latest angular cli (work in progress, any hints appreciated):

[dockerfile.txt](https://github.com/codenvy/codenvy/files/974586/dockerfile.txt)

Sorry in advance for any silly errors - hints are welcome ;-)

**Comment by hilumcool** [comment] 2017-05-03 20:55
as indicated: the error appears not always, but every now and then; tonight at this moment no error :-)

**Comment by hilumcool** [comment] 2017-05-17 20:23
@eivantsov:  Any news on that? Could you reproduce?

I just encountered the error once more, this time with Codenvy SaaS 5.10.0.

I get the impression that it's a timing problem, as the error always occured during the "first load" after the workspace has been snapshotted. After a simple browser reload everything works as expected. (I used the Dockerfile I attached you above).

**Comment by eivantsov** [comment] 2017-05-18 07:24
@hilumcool the IDE team has started investigating. We identified a few things that can be improved.

**Comment by eivantsov** [comment] 2017-07-17 05:00
Closing the issue as cannot reproduce as of 5.14.0. Now, if LS fails to start in 30 seconds, the loader goes away.

**Closed by eivantsov** 2017-07-17 05:00 UTC
Labels: kind/question
