### ISSUE TITLE
Failure of  PHP GAE deployment

### ISSUE THREAD

**Issue by chrisjj** [codenvy/codenvy#1101] opened 2016-11-05 01:42 UTC
I'm following the advice of Support:

> The new Codenvy does not have GAE plugin but you will be able to use GAE SDK natively - https://eclipse-che.readme.io/docs/che-and-gae

but that gets me an "Error: invalid_client" from Google:

![image](https://cloud.githubusercontent.com/assets/6157073/20026784/42c1dd94-a2f9-11e6-8efe-9884afa0016a.png)

What's up?

**Comment by TylerJewell** [comment] 2016-11-05 03:06
@ddementiva

**Comment by chrisjj** [comment] 2016-11-05 03:17
> @ddementiva

Please clarify.

**Comment by TylerJewell** [comment] 2016-11-05 18:36
It's how we designate the initial support person to take a look and investigate.

**Comment by chrisjj** [comment] 2016-11-06 11:38
Ah, thanks.

If there's any user here who has got the current Codenvy to successfully deploy to GAE, that would be good to hear.

**Comment by karlsson82** [comment] 2016-11-07 19:50
@chrisjj I'll give it a shot tomorrow.

**Comment by chrisjj** [comment] 2016-11-23 02:21
Two weeks on, any news?

**Comment by eivantsov** [comment] 2016-11-24 08:00
@chrisjj I cannot reproduce the error you see:

https://cannot-reprpduce-1982.appspot.com

The only bug is that it is temporarily impossible to copy the link from a terminal, so I extracted it from browser dev console:

![deployed](https://cloud.githubusercontent.com/assets/5337267/20590582/aa24f614-b22c-11e6-8329-2ac1978faf3f.png)
![code](https://cloud.githubusercontent.com/assets/5337267/20590595/bd4170a6-b22c-11e6-85bf-f1df260a900c.png)

**Comment by TylerJewell** [comment] 2017-02-09 22:57
Closing due to age and lack of reproducibilityl

**Closed by TylerJewell** 2017-02-09 22:57 UTC
Labels: kind/question
