### ISSUE TITLE
Terminal no copy paste anymore

### ISSUE THREAD

**Issue by Nicklas2751** [codenvy/codenvy#1612] opened 2017-01-26 08:52 UTC
Since a few days i can't copy and paste anything in the terminal anymore.

**Reproduction Steps:**
- Start a workspace
- Try to select something from the terminal
  - Fails
- Copy some text
- Try to paste via Strg+V
  - Fails
- Try to paste via mouse
  - Fails

**Codenvy version:**   5.1.2

**OS and version:**  
Tested on:
- Ubuntu Linux 16.10 x64 with newest Mozilla Firefox
- Microsoft Windows 10 x64 with Google Chrome
- Microsoft Windows 10 x64 with Mozilla Firefox

** Firefox developer console log:**
```
You are using the ngTouch module. 
Angular Material already has mobile click, tap, and swipe support... 
ngTouch is not supported with Angular Material!  vendor-ce07e8a724.js:75:23451

Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details.  vendor-ce07e8a724.js:75:23451

"Error: [ng:areq] Argument 'scope' is required
http://errors.angularjs.org/1.4.8/ng/areq?p0=scope&p1=required
r/<@https://codenvy.io/dashboard/scripts/vendor-ce07e8a724.js:74:380
de@https://codenvy.io/dashboard/scripts/vendor-ce07e8a724.js:74:8758
j/<@https://codenvy.io/dashboard/scripts/vendor-ce07e8a724.js:74:26828
i</<.value@https://codenvy.io/dashboard/scripts/vendor-ce07e8a724.js:754:1139
i</<.value/<@https://codenvy.io/dashboard/scripts/vendor-ce07e8a724.js:754:918
o/l<@https://codenvy.io/dashboard/scripts/vendor-ce07e8a724.js:76:13420
i@https://codenvy.io/dashboard/scripts/vendor-ce07e8a724.js:74:21352
at/d.defer/n<@https://codenvy.io/dashboard/scripts/vendor-ce07e8a724.js:74:22808
"  vendor-ce07e8a724.js:75:23451
Preloading IDE javascript /ide-resources/_app/35D4FE00FF66FAD7E8890689572E6A66.cache.js  vendor-ce07e8a724.js:734:1347

XML-Verarbeitungsfehler: Kein Wurzel-Element gefunden
Adresse: https://codenvy.io/api/workspace
Zeile Nr. 1, Spalte 1:  workspace:1:1

ZeroClipboard error of type "flash-disabled": Flash is disabled or not installed  _app-0.js

INFO (com.codenvy.plugin.pullrequest.client.workflow.ChainExecutor): Executing :: console-cpp-simple ::  =>  class com.codenvy.plugin.pullrequest.client.steps.InitializeWorkflowContextStep  _app-0.js

INFO (com.codenvy.plugin.pullrequest.client.workflow.ChainExecutor): Executing :: console-cpp-simple ::  =>  class com.codenvy.plugin.pullrequest.client.steps.DefineWorkBranchStep  _app-0.js

INFO (org.eclipse.che.ide.websocket.ng.impl.MessagesReSender): Going to resend websocket messaged: [{"jsonrpc":"2.0","method":"track:project-tree","params":{"type":"START","path":"/"}}]  _app-0.js

INFO (com.codenvy.plugin.pullrequest.client.workflow.ChainExecutor): Executing :: console-cpp-simple ::  =>  class com.codenvy.plugin.pullrequest.client.workflow.WorkflowExecutor$ChangeContextStatusStep  _app-0.js

INFO (org.eclipse.che.ide.websocket.ng.impl.MessagesReSender): Going to resend websocket messaged: [{"jsonrpc":"2.0","method":"process.getProcesses","id":"2","params":{"all":false}}]  _app-0.js

XML-Verarbeitungsfehler: Kein Wurzel-Element gefunden
Adresse: https://codenvy.io/api/activity/workspaceucmcnm3brdejf2la
Zeile Nr. 1, Spalte 1:  workspaceucmcnm3brdejf2la:1:1
```

**Comment by TylerJewell** [comment] 2017-01-27 19:34
@Nicklas2751 - I have confirmed this bug. It is seemingly a regression, though in looking through our recent commits, we are not entirely sure what could cause the regression.  Also, we are super close to merging within Eclipse Che an entirely new terminal implementation based upon xterm.js.  It does not have this problem and offers a much richer overall terminal experience.  It's the same terminal used by VS Code.  We hope to merge and ship it next week.

**Comment by eivantsov** [comment] 2017-02-20 11:33
Fixed in 5.3.0

Closing the issue. Feel free to reopen if the problem persists.

**Comment by Nicklas2751** [comment] 2017-02-20 19:10
I'm sorry but the problem still exists.

My developer tools console log:
```

          You are using the ngTouch module. 
Angular Material already has mobile click, tap, and swipe support... 
ngTouch is not supported with Angular Material!  vendor-67ce6352f2.js:75:23451
Markup '<md-button flex></md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details. vendor-67ce6352f2.js:75:23451
Unable to find the IDE javascript file to cache  vendor-67ce6352f2.js:3478:1417
"Error: [ng:areq] Argument 'scope' is required
http://errors.angularjs.org/1.4.8/ng/areq?p0=scope&p1=required
r/<@https://codenvy.io/dashboard/scripts/vendor-67ce6352f2.js:74:380
de@https://codenvy.io/dashboard/scripts/vendor-67ce6352f2.js:74:8758
D/<@https://codenvy.io/dashboard/scripts/vendor-67ce6352f2.js:74:26828
i</<.value@https://codenvy.io/dashboard/scripts/vendor-67ce6352f2.js:3498:1139
i</<.value/<@https://codenvy.io/dashboard/scripts/vendor-67ce6352f2.js:3498:918
o/l<@https://codenvy.io/dashboard/scripts/vendor-67ce6352f2.js:76:13420
i@https://codenvy.io/dashboard/scripts/vendor-67ce6352f2.js:74:21352
at/d.defer/n<@https://codenvy.io/dashboard/scripts/vendor-67ce6352f2.js:74:22808
"  vendor-67ce6352f2.js:75:23451
XML-Verarbeitungsfehler: Kein Wurzel-Element gefunden
Adresse: https://codenvy.io/api/workspace
Zeile Nr. 1, Spalte 1: workspace:1:1
INFO (com.codenvy.plugin.pullrequest.client.workflow.ChainExecutor): Executing :: MediathekViewDE ::  =>  class com.codenvy.plugin.pullrequest.client.steps.InitializeWorkflowContextStep  MediathekViewWeb:138:54
INFO (org.eclipse.che.ide.websocket.ng.impl.MessagesReSender): Going to resend websocket messaged: [{"jsonrpc":"2.0","method":"track:project-tree","params":{"type":"START","path":"/"}}, {"jsonrpc":"2.0","method":"track:git-checkout","params":{}}, {"jsonrpc":"2.0","method":"track:project-tree","params":{"type":"START","path":"/MediathekViewDE"}}, {"jsonrpc":"2.0","method":"track:project-tree","params":{"type":"START","path":"/MediathekViewDE/content"}}]  MediathekViewWeb:138:54
INFO (com.codenvy.plugin.pullrequest.client.workflow.ChainExecutor): Executing :: MediathekViewDE ::  =>  class com.codenvy.plugin.pullrequest.client.steps.DefineWorkBranchStep  MediathekViewWeb:138:54
INFO (org.eclipse.che.ide.websocket.ng.impl.MessagesReSender): Going to resend websocket messaged: [{"jsonrpc":"2.0","method":"process.getProcesses","id":"2","params":{"all":false}}]  MediathekViewWeb:138:54
INFO (com.codenvy.plugin.pullrequest.client.workflow.ChainExecutor): Executing :: MediathekViewDE ::  =>  class com.codenvy.plugin.pullrequest.client.workflow.WorkflowExecutor$ChangeContextStatusStep  MediathekViewWeb:138:54
Diese Website verwendet anscheinend einen scroll-verknüpften Positionierungseffekt. Dies könnte mit asynchronem Verschieben (Panning) schlecht zusammenspielen; siehe https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects für weitere Details und nehmen Sie an der Diskussion über damit verbundene Werkzeuge und Funktionen teil!  MediathekViewWeb
XML-Verarbeitungsfehler: Kein Wurzel-Element gefunden
Adresse: https://codenvy.io/api/activity/workspaceeqishnf2yr7vhjnq
Zeile Nr. 1, Spalte 1: workspaceeqishnf2yr7vhjnq:1:1
XML-Verarbeitungsfehler: Kein Wurzel-Element gefunden
Adresse: https://codenvy.io/api/activity/workspaceeqishnf2yr7vhjnq
Zeile Nr. 1, Spalte 1:  workspaceeqishnf2yr7vhjnq:1:1
```

The version is 5.3.0 and I'm actually retesting it with the newest Firefox 51.0.1 x64 and Google Chrome 54.0.2840.100 (64-bit) on a Ubuntu 16.10. 

I rather can' right click to paste and select for copy like on a linux terminal. And I can't select `Edit` in the menu bar and copy and past anything with it. A right click on the text to get a right click menu doesn't work too. All these three steps won't work in the editor too.

The only thing i can copy is files into folders via right click and edit menu. But in the editor i can only copy and paste via `Ctrl+C` and `Ctrl+V`. But in the terminal won't any of these methods work.

Here is a video: https://cloud.franken.de/owncloud/index.php/s/XaaoJ80dvgk7jBq

**Comment by Nicklas2751** [comment] 2017-02-21 08:00
@eivantsov I tried it, this time on a Windows 7 x64 with Firefox 52.0b7. The only thing that happened after i tried the Ctrl+Insert was that my clipboard was cleared O.o

**Comment by eivantsov** [comment] 2017-02-21 09:26
What keyboard layout do you use?

**Comment by Nicklas2751** [comment] 2017-02-21 09:34
I use the german default QWERTZ

**Comment by eivantsov** [comment] 2017-02-21 09:53
Worked for me on Win 10, German keyboard layout, Chrome and Firefox.

**Comment by Nicklas2751** [comment] 2017-02-28 07:51
Paste now works with Shift+Insert but i still can't copy anything in the console.

**Comment by eivantsov** [comment] 2017-02-28 08:06
So, Ctrl+Insert does not work for you even if you switch to English layout?

**Comment by Nicklas2751** [comment] 2017-02-28 08:18
Yes Ctrl+Insert do nothing only Shift+Insert pastes copied text.

**Comment by eivantsov** [comment] 2017-02-28 08:21
Still cannot reproduce

**Comment by rajat1saxena** [comment] 2017-03-24 08:24
This issue is still present in Codenvy.io. I just cannot copy anything from terminal, I can paste though.

**Comment by eivantsov** [comment] 2017-03-25 15:17
@rajat1saxena what is your keyboard layout and browser? I am not Win 10 now and can both copy and paste on English keyboard layout.

**Comment by rajat1saxena** [comment] 2017-03-26 02:37
@eivantsov I have tried from a Windows System and a Ubuntu system with US keyboard.

**Comment by eivantsov** [comment] 2017-03-26 02:41
I cannot reproduce. Just tried it with both Ubuntu 14.04 and Windows 10

**Comment by Nicklas2751** [comment] 2017-03-27 04:46
I still have the same problem as @rajat1saxena on Windows 10 and Ubuntu 16.10 with German and US Keyboard and on Firefox, Chromium and Chrome.

**Comment by eivantsov** [comment] 2017-03-30 12:24
At this point, I do not know how to reproduce. Tried it again on Ubuntu 14.04 (added German lang) and Windows 10 (also German).

**Comment by 4goodapp** [comment] 2017-04-01 07:45
Using It keyboard, Firefox 50, Ubuntu 16.04 based distro. Only Shift+insert works.
Am using an autocopy addon to make copies work.

**Comment by jasonberryman** [comment] 2017-04-12 15:20
I'm using ChromeOS.  There's no Insert key on the Chrome keyboard

**Comment by onyx26** [comment] 2017-04-23 07:10
I also cannot Copy & Paste in the Terminal, despite it working fine in the Editor: running on ChromeOS

When I press Crl+V it seemingly does nothing, but if I then press Return it outputs ^M

I found an excellent article on keyboard shortcuts for Copy & Paste which indicated Ctrl+Shift+V is used for Paste in some environments, and that does indeed work for me!
[https://superuser.com/questions/421463/why-does-ctrl-v-not-paste-in-bash-linux-shell](url)

**Comment by hkolvenbach** [comment] 2017-04-28 15:19
I can confirm that copy and past does **not work with in Firefox 53.0** (64bit, multiprocessor mode) on Windows 10, with neither Ctrl+Ins, Ctrl+V or Crtl+Shift+V. It does however **work in Chrome V57** with Crtl+Shift+V (but not with Ctrl+V or Ctrl+Ins). The keyboard layout (english or german) does not make a difference.

**Comment by 20avva** [comment] 2017-05-02 17:00
This also does not work in Chrome OS 57 (64-bit)
Ctrl+Shift+C does not copy, but Ctrl-Shft-V does paste.
Ctrl+V on its own doesnt work

**Comment by TylerJewell** [comment] 2017-05-02 19:16
This is like a nightmare version of whack-a-mole.  @slemeur @eivantsov @vparfonov - I am elevating this to a block issue, using my authority as Eclipse Che project lead to do this.  We solve this issue and it reappears.  What do we need to do to make this disappear permanently?

**Comment by 20avva** [comment] 2017-05-02 23:48
I'm just a high school freshman, but I think what the problem is is that the *text box* that is the terminal doesn't show up like one to the browser, which means that things can be pasted to it from the clipboard, but things cannot be copied *from* it. Maybe.

**Comment by 20avva** [comment] 2017-05-03 11:34
Something of a workaround: you can use the `touch` command from the terminal and create a temporary file in a `/projects/projectdirectory`. Then you can use the `>>` operator to append whatever you want to that file that would have normally be printed to STDOUT. Then open the file in the main editor and you can copy and paste from that. 

For example, `touch /projects/myProject/cp.txt` will create the file. `tree >> /projects/myProject/cp.txt` will append the output of `tree` to the file. Then I can open cp.txt through the file explorer and in the main editor, where copy and paste works totally fines for some odd reason. Then delete cp.txt if you'd like.

**Comment by AndrienkoAleksandr** [comment] 2017-05-03 13:22
By default xterm.js support: "CTRL + INSERT" to copy and "SHIFT + INSERT" to paste. For MAC: CMD + C and CMD +V.  And xterm.js support Ctrl + Shift + C and Ctrl + Shift + V, but for Firefox and Google Chrome this hotkeys are default for developer console and terminal didn't override it. Seems it's a bug xterm.js and we can fix it (we can override this hotkeys for terminal). @TylerJewell in the previous terminal we supported CTRL + C(if user selected text inside terminal)  to copy and CTRL + V  to paste. If user  didn't select any text then CTRL + C used to stop process. Do we need apply such behavior for xterm.js or we should fix CTRL + SHIFT + C and CTRL + SHIFT + V and that's enough?

**Comment by AndrienkoAleksandr** [comment] 2017-05-03 13:31
@eivantsov seems I found problem with issue reproduction: https://github.com/eclipse/che/issues/4990 It's another bug...

**Comment by eivantsov** [comment] 2017-05-03 14:06
@AndrienkoAleksandr I wish you were right. However, the problem does seem to be related to international keyboard layouts..

**Comment by 20avva** [comment] 2017-05-03 16:12
@eivantsov I am using a standard US (not international) keyboard and neither Ctrl+C nor Ctrl+Shift+C work. Whether or not I have text selected, Ctrl+C always stops the process

**Comment by eivantsov** [comment] 2017-05-04 10:44
@20avva Does Ctrl+Insert work for you?

**Comment by 20avva** [comment] 2017-05-04 12:17
I don't have a numeric pad on my chromebook, so I don't have an insert button either.

**Comment by onyx26** [comment] 2017-05-04 12:20
For info, I'm also using a Chromebook - UK keyboard here. Obviously to Codenvy because it's an ideal coding environment for a web-only device.

**Comment by StandBackBurrito** [comment] 2017-05-05 03:26
As a workaround on chromebook the search-period combo is insert. I can confirm that on my chromebook Ctrl-search-period will copy text from the terminal.

![image](https://cloud.githubusercontent.com/assets/1280875/25732784/bc676b0c-3118-11e7-86c6-a31e0ebaed33.png)

**Closed** 2017-05-10 12:43 UTC
Labels: kind/bug, kind/question, severity/blocker, sprint/current-sprint, team/enterprise

**Comment by peterwilli** [comment] 2017-09-21 10:11
I still cannot paste in the terminal on my ChromeBook. It's kind of a bummer since ChromeBooks are so useful with CodeEnvy. I can paste in the source code area by using `ctrl+shift+v`.

Has anyone solved this issue and if so how? Thanks!
