### ISSUE TITLE
Make it possible to provide additional workspace mount

### ISSUE THREAD

**Issue by eivantsov** [codenvy/codenvy#565] opened 2016-08-12 06:40 UTC
Some customer use cases imply mounting host directories in workspace container. Currently it is impossible both on user and admin level.

It should be possible for an installation admin to provide host paths to be mounted in workspace containers that start on a machine node.

**Comment by eivantsov** [comment] 2016-08-12 06:40
@bmicklea please comment on urgency and motivation for this issue.

**Comment by MuhamadSherif** [comment] 2016-08-12 13:40
Hi @eivantsov , yes I have the same issue since my product needs to mount to a NAS server, and after some search I found it's impossible to do that directly from the container and I need to mount the host to the NAS server first then to mount container to host.
but unfortunately I cannot do that using codenvy.

**Comment by TylerJewell** [comment] 2016-08-12 14:16
@eivantsov - I am starting to see variations of this come up from different customers.  You said specifically that an admin would need to identify the host paths.  Maybe it would be better to have two modes:
1: Admin defined, where admin must define list of all host paths available, or:
2: User defined, where the user can provide any set of host paths they would like.

How would a user who is authoring a workspace recipe know about, and be able to use these mounts?  Would they just magically work inside the workspace, or would we display something to the user, perhaps at the top of their terminal when it opens?  Something like, "# Workspace has added host mounts for x, y, and z"

**Comment by eivantsov** [comment] 2016-08-16 04:05
@TylerJewell as Codenvy On Prem admin I will not let any user mount any path - that's for sure. It's a huge risk of bringing the entire system down. A user can mount some critical Unix paths and mess up with files. 

It should be admin who defines mount paths and mode (read only?).

Just my 2 cents.

**Comment by TylerJewell** [comment] 2016-08-16 15:29
Yes, absolutely agree -it would be an admin selection only, and it would come with a lot of risk factors.

**Comment by eivantsov** [comment] 2016-08-26 09:34
@tolusha is taking care of it in this issue - https://github.com/codenvy/codenvy/issues/565

**Comment by bmicklea** [comment] 2016-08-26 13:00
Closing this as a duplicate of #499

**Closed by bmicklea** 2016-08-26 13:00 UTC
Labels: kind/enhancement
