### ISSUE TITLE
Running process is not terminated after closing in the console

### ISSUE THREAD

**Issue by artaleks9** [codenvy/codenvy#1145] opened 2016-11-15 08:16 UTC
When I stop a running process into console by closing tab process, it does not really terminate. 

**Reproduction Steps:**
* Go to dashboard and create the template 'web-java-petclinic' project from Java-MySql stack.
* Open the IDE and run the application.
* Stop application by closing tab process.
* Perform the command 'ps ax | grep tomcat8' in the terminal.

**Expected behavior:**
* Should appear the 'ask-dialog' form.
* After executing the command in the terminal we can see that process is stopped.  

**Observed behavior:**
* The 'ask-dialog' form is not appear.  
* After executing the command in the terminal we can see that process is not stopped.

**Codenvy version:** 5.0.0-M8
**OS and version:** Ubuntu 14.04

**Additional information:**
Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: Yes (sometimes need stop/start application two times that to reproduce this bug).
See the attachment.
![stop_process](https://cloud.githubusercontent.com/assets/5408906/20297862/6ea19be6-ab1b-11e6-8e06-b5c87618b65d.gif)

**Comment by dkuleshov** [comment] 2016-11-22 16:07
Hi, seems like the cause of an issue may be related to command output read timeouts. I've spotted the next line in the end of a process console output:
```
Command output read timeout is reached. Process is still running and has id 531 inside machine
```
The corresponding code is inside docker plugin: [DockerProcess.java#L169-L169](https://github.com/eclipse/che/blob/f2c8529792b2df42f5e074536ac58f3b071483c7/plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/DockerProcess.java#L169-L169)

**Comment by garagatyi** [comment] 2016-11-22 16:38
From what I see it is possible that problem is in a timeout. Probably API treat process as dead because of timeout and because of that closing console does nothing.

**Comment by mshaposhnik** [comment] 2016-11-29 09:04
Is there any reliable way to reproduce this issue ?

**Closed** 2016-11-29 12:20 UTC
Labels: kind/bug, severity/blocker, status/analyzing, team/ide, team/platform
