### ISSUE TITLE
Error: Another restore process of the same workspace is in progress

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1403] opened 2016-12-22 10:12 UTC
Got about 100 errors for 10 days in logs like:
```
2016-12-12 15:37:47,182[spaceManager-16]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 660]    - org.eclipse.che.api.core.ServerException: Start of environment ****** failed. Error: Restore of workspace workspace111111111111 failed. Another restore process of the same workspace is in progress
java.util.concurrent.ExecutionException: org.eclipse.che.api.core.ServerException: Start of environment Curvytron failed. Error: Restore of workspace workspace1111111 failed. Another restore process of the same workspace is in progress
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_45]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_45]
        at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$4(WorkspaceManager.java:639) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceManager$$Lambda$159/303085739.run(Unknown Source) [che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-5.0.0-M8.jar:5.0.0-M8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: org.eclipse.che.api.core.ServerException: Start of environment Curvytron failed. Error: Restore of workspace workspace1111111 failed. Another restore process of the same workspace is in progress
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:665) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.lambda$startAsync$1(WorkspaceRuntimes.java:245) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$$Lambda$158/1742872442.call(Unknown Source) ~[na:na]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.0.0-M8.jar:5.0.0-M8]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_45]
        ... 3 common frames omitted
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Restore of workspace workspace11111111 failed. Another restore process of the same workspace is in progress
        at com.codenvy.machine.RemoteDockerNode.bindWorkspace(RemoteDockerNode.java:143) ~[codenvy-machine-hosted-5.0.0-M8.jar:5.0.0-M8]
        at com.codenvy.machine.agent.launcher.ExternalRsyncAgentLauncherImpl.launch(ExternalRsyncAgentLauncherImpl.java:63) ~[codenvy-machine-hosted-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:604) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:676) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.doStart(WorkspaceRuntimes.java:640) ~[che-core-api-workspace-5.0.0-M8.jar:5.0.0-M8]
        ... 7 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Restore of workspace workspace111111111 failed. Another restore process of the same workspace is in progress
        at com.codenvy.machine.backup.MachineBackupManager.restoreWorkspaceBackup(MachineBackupManager.java:244) ~[codenvy-machine-hosted-5.0.0-M8.jar:5.0.0-M8]
        at com.codenvy.machine.RemoteDockerNode.bindWorkspace(RemoteDockerNode.java:133) ~[codenvy-machine-hosted-5.0.0-M8.jar:5.0.0-M8]
        ... 11 common frames omitted
```

**Reproduction Steps:**
Don't know, like run coednvy.io for several hours

**Expected behavior:**

No errors when restoring workspace.

**Observed behavior:**

Errors when restoring workspace.

**Codenvy version:** 5.0.0-M8
**OS and version:** Centos 7.2
**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Yes
Problem can be reliably reproduced: No - it's random

**Comment by mmorhun** [comment] 2017-01-11 09:14
The problem occurs when a user adds two rsync agents into his workspace:
![rsync-agents](https://cloud.githubusercontent.com/assets/15607393/21842307/d2eea832-d7ee-11e6-95ed-04a9a0426802.png)
For now, we are going to hide that agents from dashboard and refactor code later to make backup and restore processes non agents.

**Comment by riuvshin** [comment] 2017-01-11 11:04
@TylerJewell it seems we have to include this to 5.1.0 because  it is really bad thing that rsync agent could be disabled or added 2 rsync agents. that agent must be hidden from a user.

**Comment by TylerJewell** [comment] 2017-01-11 13:13
Yes confirmed. Viktor please monitor appropriately.

**Comment by garagatyi** [comment] 2017-01-11 14:23
@riuvshin it can't be disabled, just added twice or 2 different types.

**Comment by garagatyi** [comment] 2017-01-11 14:24
Related [to](https://github.com/codenvy/codenvy/issues/1510)

**Comment by TylerJewell** [comment] 2017-01-16 16:18
We have to release 5.1.0 in two days, but this is blocked.  How do we assess whether we push this out to 5.2.0, or hold it back?  This seems like it's important, but not something that would prevent a release.

**Comment by bmicklea** [comment] 2017-01-16 18:25
@vkuznyetsov - can you please explain here why this issue is `status/blocked`?

**Comment by garagatyi** [comment] 2017-01-16 18:34
@bmicklea because it should be fixed by this [issue](https://github.com/codenvy/codenvy/issues/1510)

@TylerJewell we workarounded the problem in 5.1.0-Snapshot, after upgrade to that version it should not appear. But I decided to not close this issue until it is not really fixed.

**Comment by TylerJewell** [comment] 2017-01-16 18:45
Thanks - that is clear reasoning.  We will drop the milestone and let it be added once the issues are resolved, or TLs add 5.2.0 milestone as part of their release / sprint planning.

**Comment by skryzhny** [comment] 2017-01-31 15:17
We still have lots of errors "Another restore process of the same workspace is in progress" for version 5.1.2
Looks like it isn't fixed yet, maybe we have another not identified reasons for error.

**Comment by skryzhny** [comment] 2017-02-07 10:06
Receiving errors with slightly different in content in 5.2.2
```
2017-02-06 17:19:55,111[ceSharedPool-11]  [ERROR] [DockerEnvironmentBackupManager 313]  - Restore of workspace workspace11111111111111 failed. Another restore process of the same workspace is in progress
2017-02-06 17:19:55,112[ceSharedPool-11]  [WARN ] [c.c.machine.RemoteDockerNode 101]    - The container '222222222222222222' in the workspace 'workspace111111111111' won't be backed up. The reason is that the workspace wasn't restored from backup
...
2017-02-06 17:19:55,905[ceSharedPool-11]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 774]    - Restore of workspace workspace1111111111111 failed. Another restore process of the same workspace is in progress
org.eclipse.che.api.core.ServerException: Restore of workspace workspace111111111111 failed. Another restore process of the same workspace is in progress
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.restoreBackupInsideLock(DockerEnvironmentBackupManager.java:314) ~[codenvy-machine-hosted-5.2.2.jar:5.2.2]
        at com.codenvy.machine.backup.DockerEnvironmentBackupManager.restoreWorkspaceBackup(DockerEnvironmentBackupManager.java:216) ~[codenvy-machine-hosted-5.2.2.jar:5.2.2]
        at com.codenvy.machine.RemoteDockerNode.bindWorkspace(RemoteDockerNode.java:94) ~[codenvy-machine-hosted-5.2.2.jar:5.2.2]
        at com.codenvy.machine.agent.launcher.ExternalRsyncAgentLauncherImpl.launch(ExternalRsyncAgentLauncherImpl.java:68) ~[codenvy-machine-hosted-5.2.2.jar:5.2.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.launchAgents(WorkspaceRuntimes.java:693) ~[che-core-api-workspace-5.2.2.jar:5.2.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$MachineAgentsLauncher.started(WorkspaceRuntimes.java:1054) ~[che-core-api-workspace-5.2.2.jar:5.2.2]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:806) ~[che-core-api-workspace-5.2.2.jar:5.2.2]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:260) ~[che-core-api-workspace-5.2.2.jar:5.2.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:712) ~[che-core-api-workspace-5.2.2.jar:5.2.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:105) ~[che-core-api-workspace-5.2.2.jar:5.2.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:977) [che-core-api-workspace-5.2.2.jar:5.2.2]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:941) [che-core-api-workspace-5.2.2.jar:5.2.2]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.2.2.jar:5.2.2]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
```

**Comment by bmicklea** [comment] 2017-02-14 19:52
@garagatyi and @mmorhun do we know what's causing this?  It's now affecting a sizeable number of people on codenvy.io and should be treated as a high priority sprint-interrupt.

**Comment by DanielCausebrook** [comment] 2017-02-14 20:45
I am having the same error: "Could not start workspace [name]. Reason: Start of environment 'default' failed. Error: Restore of workspace [id] failed. Another restore process of the same workspace is in progress".
It occurs a few seconds after the following appears in the dev-machine output when starting the workspace.
`[STDOUT] ⇩ Registered RpcRoutes:
[STDOUT] 
[STDOUT] Process Routes:
    ...
[STDOUT] ✓ process.getProcess
[STDOUT] ✓ process.getProcesses`

I don't have much else to add but I would like to know if there is a way to retrieve the files and projects stored within the workspace?

**Comment by bmicklea** [comment] 2017-02-14 20:53
@DanielCausebrook the team is investigating - we'll post more as we discover it.

**Comment by eivantsov** [comment] 2017-02-15 17:57
@DanielCausebrook can you give it a try again? It should be ok now.

**Comment by DanielCausebrook** [comment] 2017-02-16 00:43
Thank you very much, it boots without any issues I can see. We really appreciate the quick response on this  (and other issues like it), we might have had a busy weekend rewriting the latest changes without it!

**Closed** 2017-02-16 15:05 UTC
Labels: kind/bug, severity/blocker, sprint/current-sprint, status/in-progress, status/open-for-dev, team/platform
