### ISSUE TITLE
Workspace run doesn't work properly in all cases

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#935] opened 2016-10-08 16:51 UTC
If you right click on the ws on the left nav and say "Run", it will start running, but there is nothing displayed in the IDE.  This only happens if you have stopped the workspace from the IDE using workspace > stop

Starting workspace after it's stopped from IDE:
<img width="993" alt="screen shot 2016-10-08 at 12 46 53 pm" src="https://cloud.githubusercontent.com/assets/7644938/19214605/bf38c482-8d55-11e6-8798-a4b0116e59bf.png">

Running in left-nav, but top notification still says stopped:
<img width="975" alt="screen shot 2016-10-08 at 12 49 46 pm" src="https://cloud.githubusercontent.com/assets/7644938/19214606/c2d9ee40-8d55-11e6-89fb-87a0824804ad.png">

**Codenvy version:** 5.0.0-M5
**OS and version:** beta.codenvy.com

**Comment by slemeur** [comment] 2016-10-09 07:55
Please @vitaliy-guliy + @akurinnoy  give a look to this issue

**Comment by slemeur** [comment] 2016-10-10 07:14
This will be taken as part of #932.
The issue is connected

**Comment by vitaliy-guliy** [comment] 2016-10-18 14:44
Fixed by commit
https://github.com/codenvy/codenvy/commit/a64f05399347d75e42c8f25de14a097c938468e9

**Comment by vitaliy-guliy** [comment] 2016-10-18 14:44
Spent 1 day on investigation

**Closed** 2016-10-18 14:44 UTC
Labels: kind/bug, severity/blocker, sprint/current-sprint, team/plugin
