### ISSUE TITLE
Terminal consuming cout strings

### ISSUE THREAD

**Issue by scifuentes** [codenvy/codenvy#1889] opened 2017-03-06 21:47 UTC
**Reproduction Steps:**
A simple .cpp, compiled with g++ (g++ -g -std=c++11 -Wall)

```
#include <iostream>
int main()
{
    std::cout << "Foo<Bar>" << std::endl;  
    return 0;
}
```

The result in the Terminal is just ...

> Foo

**Codenvy version:**    
5.4.0
**OS and version:**    
Windows 7 & Chrome

**Docker version:**    

**Codenvy cli.log output:**

**Comment by eivantsov** [comment] 2017-03-07 07:40
Duplicate of https://github.com/eclipse/che/issues/3091

**Closed by eivantsov** 2017-03-07 07:40 UTC
