### ISSUE TITLE
Error NullPointerException at org.eclipse.che.api.workspace.server.DtoConverter

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1969] opened 2017-03-21 15:21 UTC
Got this exception in log like several times per month:
```
2017-03-20 02:17:12,163[nio-8080-exec-4]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2017-03-20 02:17:12
java.lang.NullPointerException: null
        at org.eclipse.che.api.workspace.server.DtoConverter.asDto(DtoConverter.java:68) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.workspace.server.DtoConverter.asDto(DtoConverter.java:62) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.workspace.server.WorkspaceService.lambda$getWorkspaces$1(WorkspaceService.java:222) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_111-internal]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_111-internal]
        at java.util.Vector$VectorSpliterator.forEachRemaining(Vector.java:1414) ~[na:1.8.0_111-internal]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_111-internal]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_111-internal]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_111-internal]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_111-internal]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_111-internal]
        at org.eclipse.che.api.workspace.server.WorkspaceService.getWorkspaces(WorkspaceService.java:223) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at sun.reflect.GeneratedMethodAccessor165.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111-internal]
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.RequestDispatcher.invokeResourceMethod(RequestDispatcher.java:268) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:198) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120) [everrest-core-1.13.3.jar:na]
        at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61) [everrest-core-1.13.3.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:na]
        at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:436) [catalina.jar:8.0.38]
        at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:177) [catalina.jar:8.0.38]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
        at com.codenvy.api.license.filter.SystemLicenseLoginFilter.doFilter(SystemLicenseLoginFilter.java:118) [codenvy-hosted-api-system-license-filters-5.5.0.jar:5.5.0]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
        at com.codenvy.auth.sso.client.DefaultTokenHandler.handleValidToken(DefaultTokenHandler.java:65) [codenvy-hosted-sso-client-5.5.0.jar:5.5.0]
        at com.codenvy.api.permission.server.PermissionTokenHandler.handleValidToken(PermissionTokenHandler.java:64) [codenvy-hosted-authorization-5.5.0.jar:5.5.0]
        at com.codenvy.auth.sso.client.LoginFilter.doFilter(LoginFilter.java:120) [codenvy-hosted-sso-client-5.5.0.jar:5.5.0]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) [guice-servlet-4.1.0.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.38]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.38]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.38]
        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:189) [logback-access-1.1.2.jar:na]
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.38]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528) [catalina.jar:8.0.38]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100) [tomcat-coyote.jar:8.0.38]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687) [tomcat-coyote.jar:8.0.38]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520) [tomcat-coyote.jar:8.0.38]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476) [tomcat-coyote.jar:8.0.38]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.38]
```

**Reproduction Steps:**
Don't know

**Codenvy version:**  5.5.1

**Comment by mshaposhnik** [comment] 2017-04-14 13:13
User actions log: started temporary workspace from test-stack page:
```
190.42.23.228 - - [20/Mar/2017:02:12:18 +0000] "POST /api/workspace/runtime?temporary=true HTTP/1.1" 200 -
190.42.23.228 - - [20/Mar/2017:02:12:18 +0000] "GET /alexpanli5/test-wksp-uy6a HTTP/1.1" 200 -
190.42.23.228 - - [20/Mar/2017:02:12:18 +0000] "GET /_app/browserNotSupported.js HTTP/1.1" 200 3242
190.42.23.228 - - [20/Mar/2017:02:12:18 +0000] "GET /_app/_app.nocache.js HTTP/1.1" 200 7851
190.42.23.228 - - [20/Mar/2017:02:12:19 +0000] "GET /_app/IDE.css HTTP/1.1" 200 3870
190.42.23.228 - - [20/Mar/2017:02:12:19 +0000] "GET /_app/F6B640B99E7CBB94CF87FF9702CB7F47.cache.js HTTP/1.1" 200 -
190.42.23.228 - - [20/Mar/2017:02:12:21 +0000] "GET /_app/font-awesome-4.5.0/css/font-awesome.min.css HTTP/1.1" 200 -
190.42.23.228 - - [20/Mar/2017:02:12:22 +0000] "GET /_app/ZeroClipboard.min.js HTTP/1.1" 200 -
190.42.23.228 - - [20/Mar/2017:02:12:22 +0000] "GET /api/preferences HTTP/1.1" 200 -
190.42.23.228 - - [20/Mar/2017:02:12:22 +0000] "GET /api/profile/ HTTP/1.1" 200 998
190.42.23.228 - - [20/Mar/2017:02:12:22 +0000] "GET /api/workspace/alexpanli5/test-wksp-uy6a HTTP/1.1" 200 -
190.42.23.228 - - [20/Mar/2017:02:12:23 +0000] "GET /api/ws HTTP/1.1" 101 -
190.42.23.228 - - [20/Mar/2017:02:12:23 +0000] "GET /api/project-template/all HTTP/1.1" 200 -
190.42.23.228 - - [20/Mar/2017:02:12:27 +0000] "GET /_app/font-awesome-4.5.0/fonts/fontawesome-webfont.woff2?v=4.5.0 HTTP/1.1" 200 66624
190.42.23.228 - - [20/Mar/2017:02:12:27 +0000] "GET /_app/ZeroClipboard.swf?noCache=1489975945229 HTTP/1.1" 200 4036
190.42.23.228 - - [20/Mar/2017:02:12:28 +0000] "GET /api/workspace/workspacevk4s9rj88s7zk8hj HTTP/1.1" 200 -
190.42.23.228 - - [20/Mar/2017:02:12:28 +0000] "GET /api/bitbucket/endpoint HTTP/1.1" 200 -
190.42.23.228 - - [20/Mar/2017:02:12:28 +0000] "GET /_app/require.js HTTP/1.1" 200 -
190.42.23.228 - - [20/Mar/2017:02:12:28 +0000] "GET /_app/activity.js HTTP/1.1" 200 1870
190.42.23.228 - - [20/Mar/2017:02:12:28 +0000] "GET /_app/term/xterm.js HTTP/1.1" 200 -
190.42.23.228 - - [20/Mar/2017:02:12:58 +0000] "PUT /api/activity/workspacevk4s9rj88s7zk8hj HTTP/1.1" 204 -
190.42.23.228 - - [20/Mar/2017:02:13:08 +0000] "GET /api/workspace/workspacevk4s9rj88s7zk8hj HTTP/1.1" 200 -
190.42.23.228 - - [20/Mar/2017:02:13:08 +0000] "GET /api/workspace/workspacevk4s9rj88s7zk8hj HTTP/1.1" 200 -
190.42.23.228 - - [20/Mar/2017:02:13:08 +0000] "GET /api/machine/token/workspacevk4s9rj88s7zk8hj HTTP/1.1" 200 228
190.42.23.228 - - [20/Mar/2017:02:13:09 +0000] "GET /api/machine/token/workspacevk4s9rj88s7zk8hj HTTP/1.1" 200 228
190.42.23.228 - - [20/Mar/2017:02:13:28 +0000] "PUT /api/activity/workspacevk4s9rj88s7zk8hj HTTP/1.1" 204 -
190.42.23.228 - - [20/Mar/2017:02:13:58 +0000] "PUT /api/activity/workspacevk4s9rj88s7zk8hj HTTP/1.1" 204 -
190.42.23.228 - - [20/Mar/2017:02:15:28 +0000] "PUT /api/activity/workspacevk4s9rj88s7zk8hj HTTP/1.1" 204 -
190.42.23.228 - - [20/Mar/2017:02:16:28 +0000] "PUT /api/activity/workspacevk4s9rj88s7zk8hj HTTP/1.1" 204 -
190.42.23.228 - - [20/Mar/2017:02:16:58 +0000] "PUT /api/activity/workspacevk4s9rj88s7zk8hj HTTP/1.1" 204 -
190.42.23.228 - - [20/Mar/2017:02:17:09 +0000] "DELETE /api/workspace/workspacevk4s9rj88s7zk8hj/runtime?create-snapshot=false HTTP/1.1" 204 -
190.42.23.228 - - [20/Mar/2017:02:17:11 +0000] "GET /api/stack?maxItems=50 HTTP/1.1" 304 -
190.42.23.228 - - [20/Mar/2017:02:17:11 +0000] "GET /api/license/system/legality HTTP/1.1" 304 -
190.42.23.228 - - [20/Mar/2017:02:17:11 +0000] "GET /api/permissions/system HTTP/1.1" 404 -
190.42.23.228 - - [20/Mar/2017:02:17:11 +0000] "GET /api/organization HTTP/1.1" 304 -
190.42.23.228 - - [20/Mar/2017:02:17:11 +0000] "GET /api/license/system/legality HTTP/1.1" 304 -
190.42.23.228 - - [20/Mar/2017:02:17:12 +0000] "GET /api/permissions/system HTTP/1.1" 404 -
190.42.23.228 - - [20/Mar/2017:02:17:12 +0000] "GET /api/factory/find?creator.userId=userslahqpn703uhbe87&maxItems=5&skipCount=0 HTTP/1.1" 304 -
190.42.23.228 - - [20/Mar/2017:02:17:12 +0000] "GET /api/license/account/organizationbslplocy42d4dfdi HTTP/1.1" 304 -
190.42.23.228 - - [20/Mar/2017:02:17:12 +0000] "GET /api/workspace HTTP/1.1" 500 -
```

**Comment by mshaposhnik** [comment] 2017-04-20 08:03
Since we can not reproduce issue manually, and since 5.5.0 we did a lot of fixes to improve DB performance and integrity, we're closing issue right now, but continue to monitor if similar  errors are happened.

**Closed by mshaposhnik** 2017-04-20 08:03 UTC
Labels: kind/bug, sprint/next-sprint, status/open-for-dev, team/platform
