### ISSUE TITLE
No syntax highlight on  header files (.h)

### ISSUE THREAD

**Issue by scifuentes** [codenvy/codenvy#1881] opened 2017-03-05 15:59 UTC
**Reproduction Steps:**
new, default cpp workspace. Create a new .h file

**Codenvy version:**    
5.4.0

**OS and version:**    
Windows

**Docker version:**    

**Codenvy cli.log output:**

**Comment by TylerJewell** [comment] 2017-04-17 16:28
duplicate of eclipse che issue

**Closed by TylerJewell** 2017-04-17 16:28 UTC
Labels: kind/enhancement
