### ISSUE TITLE
cli:nightly download doesn't download newer images

### ISSUE THREAD

**Issue by gbatalski** [codenvy/codenvy#1501] opened 2017-01-10 18:43 UTC
The `cli:nightly download` command doesn't download newer nightly images even if they are available.

Also i'm getting the message

>  WARN: There is a newer codenvy/cli:nightly image on DockerHub.

but this time it's not true: cli:nightly is the newest one.

I remember, it does work last week.

**Reproduction Steps:**

**Codenvy version:**    
current as of 2017-01-10
**OS and version:**    
Ubuntu 16.10
**Docker version:**    
1.12.1
**Codenvy cli.log output:**

**Comment by TylerJewell** [comment] 2017-01-10 18:46
This is related to this issue:
https://github.com/eclipse/che/issues/3640

**Comment by TylerJewell** [comment] 2017-01-10 18:49
@gbatalski - Gena, thanks for posting this.  Using the nightly is really discouraged unless you are one of our engineers, as we have mutability problems with traceability of images.  Our images depend upon other images which depend upon other images.  It's a big chain of stuff.  And there are severe limits on DockerHub in that the "created" date that is in DockerHub does not actually show you when the image was created, just when it was uploaded.  This date is not hte same as the "created" date on the nightly image on your disk - so comparing these values sometimes generates wrong warning messages.

We are going to change the Eclipse Che CLI so that if you are using nightly it always does a force pull, and we will start to analyze the date that nightly image was written to your disk and if it's >24 hours, we will stop execution and force a new nightly download.  It's not ideal, but seems to be our best choice here.

**Comment by gbatalski** [comment] 2017-01-10 18:59
ok, thanks. Would you close this issue?

**Comment by TylerJewell** [comment] 2017-01-10 19:02
No, probably not - I don't mind keeping it open as a tracking issue for Codenvy.  We have to issue separate pull requests for both Che and Codenvy, and once the Che improvements are made, then we can cross-link to here and perform a round of testing.

**Comment by TylerJewell** [comment] 2017-01-10 19:03
How are you enjoying the running of Codenvy with the new CLI, by the way?

**Comment by gbatalski** [comment] 2017-01-10 20:22
Thanks for asking! The installtion is quite simple, the config is straitforward. I'm evaluating codenvy for our team, but i don't have too much time to dive deeply enough. I've tried a nightly because of tree jumping issue: i hoped to find it corrected but strumbled over the issue with docker 1.12.1 on ubuntu 16.10 (insecure registry as described [here](http://stackoverflow.com/questions/38695515/can-not-pull-push-images-after-update-docker-to-1-12])). The other issue with nightly (not reprodusable at codenvy.io) is AltGr+Q (german keyboard)  in a concole view doesn't produce @ , so i need to copy-paste the @ character to connect via ssh ;-)). But i don't give up: Currently i'm only having a Surface to work and local eclipse would kill this small device. I'm not expecting too much development activity for me, but a lot of configuration, deployment, testing, documenting  (also underway). So i hope, codenvy (or even che) is the way to clone/review something quickly and test/correct deployments. As soon as i understand che/codenvy more, it could be alternative for my mates to complete our cloud based dev environment with the cloud ide.

May i ask, does your team (Codenvy/Che developers) work with codenvy/che daily?

**Comment by TylerJewell** [comment] 2017-01-10 20:28
Interestingly - just today one of our PMs was finally able to reproduce the tree jumping issue, so it is now something that can be properly investigated by R&D.

We have 45 employees, of which about 40 of them are technical.  All 40 of those employees work on Eclipse Che and Codenvy every day - working to make it a really good system. Che 5 which was tagged last week has 1300 commits from almost 70 contributors world wide. So there is a lot of activity on these projects and you will see many commits each day.

The Dockerized installation of a clustered Codenvy is brand new. We had a lot of our engineers working on this for months. we've gone from doing an installation of Codenvy in days or hours to doing it on any OS in a matter of minutes now.  As a result, anyone anywhere can run Che or Codenvy with simple syntax.  Really changes the way that software could be handled in the future.

**Comment by gbatalski** [comment] 2017-01-10 20:37
Thank you for the good job! I wish you every success!

**Comment by TylerJewell** [comment] 2017-01-11 16:40
https://github.com/eclipse/che/pull/3671
Merged to master - we now will automatically pull these.

**Closed by TylerJewell** 2017-01-11 16:40 UTC
Labels: kind/question
