### ISSUE TITLE
Instance started via CLI on Fedora linux fails on curl() command

### ISSUE THREAD

**Issue by mlabuda** [codenvy/codenvy#1374] opened 2016-12-19 11:42 UTC
[Short description of problem here]

I am trying to run nightly instance of codenvy via CLI start, but it does not get ready because of using wrong curl command. It uses '/usr/bin/curl  "-I -k 172.17.0.1/api/ -s -o /dev/null --write-out %{http_code}"' instead of '/usr/bin/curl  -I -k 172.17.0.1/api/ -s -o /dev/null --write-out %{http_code}'. Double quotes make start fail on startup.

**Reproduction Steps:**

[ASSERT]
Be on Linux OS.
[EXEC]
Start nightly codenvy. I used
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/mlabuda/mount_volumes:/data codenvy/cli:nightly start
[RESULT]
See fail on timeout:
ERROR: (codenvy start): Timeout waiting for server. Run "docker logs codenvy_codenvy_1" to inspect the issue.

**Expected behavior:**

Codenvy get notifed about correct http code and get started without failure.

**Observed behavior:**

Start up fail on timeout.

**Codenvy version:** [Enter Codenvy version here]
**OS and version:** [Enter OS name and version here]

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: Don't know
Problem can be reliably reproduced: Yes

**Comment by TylerJewell** [comment] 2016-12-19 14:30
Fixed in Eclipse Che - https://github.com/eclipse/che/pull/3424/files.  Please test this branch.

**Comment by TylerJewell** [comment] 2016-12-27 00:14
We figured out that this was a firewall issue and not a bug.

**Closed by TylerJewell** 2016-12-27 00:14 UTC
Labels: kind/bug
