### ISSUE TITLE
Maven proxy authentication settings 

### ISSUE THREAD

**Issue by diogosaad** [codenvy/codenvy#1897] opened 2017-03-07 17:17 UTC
Maven build fails when behind proxy which requires authentication.
Output message is: "Caused by: org.apache.maven.wagon.authorization.AuthorizationException: Not authorized by proxy . ReasonPhrase: Proxy Authentication Required.

By adding -X to mvn I could check that maven_home is set to /home/user/apache-maven-3.3.9 and the settings file under conf does not have any proxy configuration. **However** I can see http_proxy and https_proxy environment variables properly set (coming from host machine).

**Reproduction Steps:**
Create a new workspace with Java Stack and a Ready-to-run "console-java-simple" project.
Click on Build command.

**Codenvy version:**    5.5.0-SNAPSHOT

**OS and version:**    RH Enterprise Server 7.3

**Docker version:**  1.13.0 for Client and Server  

**Codenvy cli.log output:** 
HTTP/1.0 200 OK
Content-type: application/octet-stream
Date: Tue, 07 Mar 2017 16:37:30 GMT
Connection: close
Accept-Ranges: bytes
Last-Modified: Tue, 08 Nov 2016 19:28:30 GMT
Content-length: 6

         conn (browser => ws):    [0;32m[OK][0m
         conn (server => ws):     [0;32m[OK][0m
fakeagent

INFO: (che start):  Starting containers...
docker_compose --file="/data/instance/docker-compose-container.yml" -p="che" up -d >> "/data/cli.log" 2>&1
Creating che
docker inspect -f '{{.Id}}' che
INFO: (che start):  Services booting...
INFO: (che start):  Server logs at "docker logs -f che"
DEBUG: Container with id 87292db1e915 is matching che service
DEBUG: Running state of container 87292db1e915 is true
/usr/bin/curl --noproxy 10.58.142.193 "-I -k 10.58.142.193:8080/api/ -s -o /dev/null --write-out %{http_code}"
000
sleep 2
/usr/bin/curl --noproxy 10.58.142.193 "-I -k 10.58.142.193:8080/api/ -s -o /dev/null --write-out %{http_code}"
200
DEBUG: Container with id 87292db1e915 is matching che service
DEBUG: Running state of container 87292db1e915 is true
docker inspect -f '{{.Id}}' che
/usr/bin/curl --noproxy 10.58.142.193 "-I -k 10.58.142.193:8080/api/ -s -o /dev/null --write-out %{http_code}"
200
docker inspect -f '{{.Id}}' che
/usr/bin/curl --noproxy 10.58.142.193 "-I -k 10.58.142.193:8080/api/ -s -o /dev/null --write-out %{http_code}"
200
INFO: (che start):  Booted and reachable
INFO: (che start):  Ver: nightly
INFO: (che start):  Use: http://10.58.142.193:8080
INFO: (che start):  API: http://10.58.142.193:8080/swagger

**Comment by TylerJewell** [comment] 2017-03-07 23:23
Hi @diogosaad -in 5.4, we introduced a MAVEN_OPTIONS configuration parameters in the `codenvy.env` that allows you to set the parameters that are passed into the JVM that maven uses to do its magic. You may not be aware, but JVMs do not naturally inherit `http_proxy` and related variables from the OS' environment.  This "limitation" of Java has on many occassions caused us a variety of heart ache in the normal execution of Codenvy in firewalled environments.

Have you looked at configuring this property for your specific environment?

**Comment by eivantsov** [comment] 2017-03-08 16:06
@TylerJewell, MAVEN_OPTS=$JAVA_OPTS by default - https://github.com/codenvy/codenvy/blob/02cdd3797fd1bbbad0d524fb34eab97b0b09fb18/dockerfiles/init/manifests/codenvy.env#L310-L313

Since we inherit everything from a Docker daemon, @diogosaad have you configured your Docker to be using proxy with password? Sharing your codenvy.env file will help!

**Comment by mvidhya86** [comment] 2017-03-13 04:43
Hi,
I'm in Diogo's team. Please find the env file attached. 
Docker is configured to use proxy with password. And this is done as in this link - https://crondev.com/running-docker-behind-proxy/

**Comment by eivantsov** [comment] 2017-03-13 06:11
@mvidhya86 I do not see any file attached. 

Also, can you runn `env | grep OPTS` in a workspace terminal?

**Comment by mvidhya86** [comment] 2017-03-13 06:50
Hi,

Please find the file attached.
Sorry, I noticed that I have some issues in file upload in GitHub

Best regards

Vidhya Murali
RBEI/ETC3

Tel. +91(80)6136-1909

**Comment by eivantsov** [comment] 2017-03-13 06:58
Can you run `env | grep OPTS` in a running workspace please?

**Comment by eivantsov** [comment] 2017-03-13 07:00
Also, are we talking about Codenvy or Che? The env file you have shared is for Che.

**Comment by mvidhya86** [comment] 2017-03-13 07:09
Hi,
Please find the details below on running env | grep OPTS in workspace terminal
MAVEN_OPTS – same as JAVA_OPTS

JAVA_OPTS=-Xms256m -Xmx2048m -Djava.security.egd=file:/dev/./urandom -Dhttp.prox
ySet=true -Dhttp.proxyUser=xxxx -Dhttp.proxyPassword=xxxx -Dhttp.prox
yHost=xxxx -Dhttp.proxyPort=8080 -Dhttps.proxyUser=xxxx
-Dhttps.proxyPassword=xxxx -Dhttps.proxyHost=xxxx
-Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts='che-host||10.58.142.192|'


Thank You.

Best regards

Murali Vidhya
RBEI/ETC3

Tel. +91(80)6136-1909

**Comment by eivantsov** [comment] 2017-03-13 07:39
Can you import projects and use Git? I mean are JAVA_OPTS ok for you?

**Comment by mvidhya86** [comment] 2017-03-13 08:39
Am able to import project from GIT. But maven build of the imported project still fails with the same proxy error
‘Not authorized by proxy, ReasonPhrase: Proxy Authentication required’

**Comment by mvidhya86** [comment] 2017-03-13 13:01
Hi,

Do we need to have proxy in  both the places - code envy env file and also in settings.xml inside workspace. Could you confirm this, as i get Build Success only proxy is applied to /home/user/.m2 settings.xml.

**Comment by eivantsov** [comment] 2017-03-13 13:35
Yes, settings.xml will work. However, I wonder why MAVEN_OPTS do not.

How do you configure your maven locally? settings.xml?

**Comment by mvidhya86** [comment] 2017-03-13 13:41
Ya, but i would like to avoid using this proxy configuration in /home/user/local/.m2 and /home/user/apache-maven -3.3.9.  Is there a way to achieve Build only by MAVEN_OPTS

**Comment by eivantsov** [comment] 2017-03-13 13:45
Hm.. MAVEN_OPTS are totally ok. I have tested it with passwordless proxy. Looks like I need to give it a shot with proxy that requires password.

**Comment by mvidhya86** [comment] 2017-03-13 13:46
Ok, i will wait for your reply

**Comment by eivantsov** [comment] 2017-03-15 11:43
@mvidhya86 I have reproduced the issue. There are two findings:

1. Openjdk has issues with password protected proxies
2. Oracle JDK does not have any issues and Java works OK.
3. Maven does not seem to pick up username and password when connecting to proxy.

We need to investigate this, so it will take some time. Meanwhile, building a stack with a custom settings.xml or having it in your projects is a workaround.

**Comment by eivantsov** [comment] 2017-07-17 05:44
I am going to close this one, since proxy settings are correctly set by Che, so the environment itself is OK. To verify this, one may just run `eclipse/ubuntu_jdk8` image manually, set MAVEN_OPTS with the right proxy settings and try  to build a project.

In addition to that, specifying proxies in `settings.xml` works as expected.

**Closed by eivantsov** 2017-07-17 05:44 UTC
Labels: kind/bug, kind/eclipse-che
