### ISSUE TITLE
API don't remove container when entrypoint is invalid and conatainer state is "Exited"

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#563] opened 2016-08-11 12:50 UTC
I see lot of containers in "Exited" states.
Swarm reserves memory for them and can't start new containers because of this

```
# docker -H localhost:23750 ps -a
9fa8d23057a7        eclipse-che/workspaceq6smjp9olk5fyml9_machinet8tnel41ogr2lce4_brittjohalloran_ws-machine       "R"                      48 minutes ago      Exited (2) 48 minutes ago                                                                                                                                                                                          node3.beta.codenvy.com/workspaceq6smjp9olk5fyml9_machinet8tnel41ogr2lce4_brittjohalloran_ws-machine
5bc463a59c79        eclipse-che/workspaceq6smjp9olk5fyml9_machine8q8s9kq2rug3ip1t_brittjohalloran_ws-machine       "R"                      48 minutes ago      Exited (2) 48 minutes ago                                                                                                                                                                                          node2-beta.codenvy-stg.com/workspaceq6smjp9olk5fyml9_machine8q8s9kq2rug3ip1t_brittjohalloran_ws-machine
```
You may see invalid entrypoint. So probably container exits immediately after start.
API should detect that situation and remove workspace.

Reproduction Steps:
Start workspace with invalid entrypoint

Expected behavior:
Workspace should be  stopped and corresponding container should be removed

Observed behavior:
Containers stays in "Excited" state

Codenvy version: customer-SaaS-4.6.2
OS and version: Centos 7.2

**Comment by TylerJewell** [comment] 2016-08-11 12:56
Is this is a duplicate to #562?

**Comment by garagatyi** [comment] 2016-08-11 12:58
yes

**Comment by garagatyi** [comment] 2016-08-11 12:58
Close be cause this issue is duplicate of #562

**Closed by garagatyi** 2016-08-11 12:58 UTC
Labels: kind/bug
