### ISSUE TITLE
cannot use codenvy.sh via symlink

### ISSUE THREAD

**Issue by mkuznyetsov** [codenvy/codenvy#1118] opened 2016-11-08 14:50 UTC
**Reproduction Steps:**

Create symlink /usr/bin/codenvy for your codenvy.sh

**Observed behavior:**

All commands fail, here is the output:

INFO: (codenvy cli): Pulling image eclipse/che-version
sh: can't create /copy/test: Is a directory

**Codenvy version:** hackaton branch
**OS and version:** Ubuntu 14.04

**Additional information:**

Problem can be reliably reproduced: [Yes]

**Comment by skabashnyuk** [comment] 2016-11-08 14:55
fix tested on  macOS
```
get_script_source_dir() {
  SOURCE="${BASH_SOURCE[0]}"
  while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done
  echo "$( cd -P "$( dirname "$SOURCE" )" && pwd )»
}
```

**Comment by TylerJewell** [comment] 2016-11-08 14:55
Did you test on windows?

**Comment by TylerJewell** [comment] 2016-11-08 14:56
Also, the che.sh in the `cli-refactoring` branch has the same function, so it needs to be consolidated.

**Comment by skabashnyuk** [comment] 2016-11-08 14:57
>Did you test on windows?
I've asked @eivantsov. He promised to test.

**Comment by TylerJewell** [comment] 2016-11-08 14:59
Developers should have access to windows VMs so that they can spin these up and test themselves quickly.  It's the same way that I spin up digital ocean boxes to test linux scenarios.

**Comment by garagatyi** [comment] 2016-11-08 15:25
I suppose we can not use windows without license, so it is better to have access to a real PC/laptop with windows or have cloud-based VMs with installed windows

**Comment by skabashnyuk** [comment] 2016-11-09 08:10
AFAIK we tested this change on Windows and didn't see any regression. I will introduce PR after @garagatyi  will merge https://github.com/eclipse/che/pull/3013

**Comment by TylerJewell** [comment] 2016-11-09 10:21
Add this to changes in Che's cli-refactoring branch as well which has a duplicate of this cli functionality.

**Comment by garagatyi** [comment] 2016-11-15 12:24
Closing this issue since cli was moved to container

**Closed by garagatyi** 2016-11-15 12:24 UTC
Labels: kind/bug
