### ISSUE TITLE
NPE in logs at org.eclipse.che.api.workspace.server.WorkspaceManager.stopWorkspace

### ISSUE THREAD

**Issue by skryzhny** [codenvy/codenvy#1971] opened 2017-03-21 15:50 UTC
Got this error:
```
2017-03-18 18:58:53,355[io-8080-exec-36]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2017-03-18 18:58:53
java.lang.NullPointerException: null
        at org.eclipse.che.api.workspace.server.WorkspaceManager.stopWorkspace(WorkspaceManager.java:530) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at org.eclipse.che.api.workspace.server.WorkspaceService.stop(WorkspaceService.java:376) ~[che-core-api-workspace-5.5.0.jar:5.5.0]
        at sun.reflect.GeneratedMethodAccessor347.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111-internal]
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:140) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:60) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.RequestDispatcher.doInvokeResource(RequestDispatcher.java:306) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:297) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:233) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.RequestDispatcher.dispatch(RequestDispatcher.java:128) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:62) ~[everrest-core-1.13.3.jar:na]
        at org.everrest.core.impl.EverrestProcessor.process(EverrestProcessor.java:120) [everrest-core-1.13.3.jar:na]
        at org.everrest.core.servlet.EverrestServlet.service(EverrestServlet.java:61) [everrest-core-1.13.3.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:na]
        at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:436) [catalina.jar:8.0.38]
        at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:177) [catalina.jar:8.0.38]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
        at com.codenvy.api.license.filter.SystemLicenseLoginFilter.doFilter(SystemLicenseLoginFilter.java:118) [codenvy-hosted-api-system-license-filters-5.5.0.jar:5.5.0]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
        at com.codenvy.auth.sso.client.DefaultTokenHandler.handleValidToken(DefaultTokenHandler.java:65) [codenvy-hosted-sso-client-5.5.0.jar:5.5.0]
        at com.codenvy.api.permission.server.PermissionTokenHandler.handleValidToken(PermissionTokenHandler.java:64) [codenvy-hosted-authorization-5.5.0.jar:5.5.0]
        at com.codenvy.auth.sso.client.LoginFilter.doFilter(LoginFilter.java:120) [codenvy-hosted-sso-client-5.5.0.jar:5.5.0]
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:na]
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) [guice-servlet-4.1.0.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.38]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.38]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.38]
        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:189) [logback-access-1.1.2.jar:na]
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676) [catalina.jar:8.0.38]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.38]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528) [catalina.jar:8.0.38]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100) [tomcat-coyote.jar:8.0.38]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687) [tomcat-coyote.jar:8.0.38]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520) [tomcat-coyote.jar:8.0.38]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476) [tomcat-coyote.jar:8.0.38]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.38]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
```

**Reproduction Steps:**
Don't know

**Codenvy version:**    5.5.1

**Comment by mshaposhnik** [comment] 2017-04-12 09:23
The cause:
94.217.59.192 - - [18/Mar/2017:18:58:53 +0000] "DELETE /api/workspace/workspace7yt2h17zokh4bd0x/runtime?create-snapshot=false HTTP/1.1" 500 -

**Comment by mshaposhnik** [comment] 2017-04-12 10:49
Some additional info:
```
root@codenvy 03]# grep workspace7yt2h17zokh4bd0x */cata* 18/catalina-0.log:2017-03-18 18:48:44,911[io-8080-exec-31]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 892]    - Workspace 'jlkonjl/test-wksp-1o1m' with id 'workspace7yt2h17zokh4bd0x' created by user 'jlkonjl' 18/catalina-0.log:2017-03-18 18:52:55,595[ceSharedPool-13]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 692]   - Launching 'org.eclipse.che.ssh' agent at workspace workspace7yt2h17zokh4bd0x 18/catalina-0.log:2017-03-18 18:52:57,819[ceSharedPool-13]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 692]   - Launching 'com.codenvy.rsync_in_machine' agent at workspace workspace7yt2h17zokh4bd0x 18/catalina-0.log:2017-03-18 18:52:58,790[ceSharedPool-13]  [ERROR] [DockerEnvironmentBackupManager 509]  - Error occurred during backup/restore of workspace 'workspace7yt2h17zokh4bd0x' on node 'node16.codenvy.io' : Warning: Permanently added '[node16.codenvy.io]:37925,[172.30.12.116]:37925' (ECDSA) to the list of known hosts. 18/catalina-0.log:2017-03-18 18:52:58,792[ceSharedPool-13]  [WARN ] [c.c.machine.RemoteDockerNode 101]    - The container '283db099712369479c7151f3c8c8761395b8efcec308dc6c0b9e3aec82482d01' in the workspace 'workspace7yt2h17zokh4bd0x' won't be backed up. The reason is that the workspace wasn't restored from backup 18/catalina-0.log:2017-03-18 18:53:00,752[ceSharedPool-13]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 779]    - Restoring of workspace workspace7yt2h17zokh4bd0x filesystem terminated on node16.codenvy.io node. Synchronization process failed. Exit code 255 18/catalina-0.log:org.eclipse.che.api.core.ServerException: Restoring of workspace workspace7yt2h17zokh4bd0x filesystem terminated on node16.codenvy.io node. Synchronization process failed. Exit code 255
```

**Comment by mshaposhnik** [comment] 2017-04-12 11:16
Another case:
```2017-04-03 18:35:38,683[nio-8080-exec-1]  [ERROR] [c.a.c.r.RuntimeExceptionMapper 47]   - Internal Server Error occurred, error time: 2017-04-03 18:35:38
java.lang.NullPointerException: null
        at org.eclipse.che.api.workspace.server.WorkspaceManager.stopWorkspace(WorkspaceManager.java:530) ~[che-core-api-workspace-5.6.0.jar:5.6.0]
        at org.eclipse.che.api.workspace.server.WorkspaceService.stop(WorkspaceService.java:376) ~[che-core-api-workspace-5.6.0.jar:5.6.0]
        at sun.reflect.GeneratedMethodAccessor335.invoke(Unknown Source) ~[na:na]
```

**Comment by mshaposhnik** [comment] 2017-04-14 13:13
Users action log: started a temporary workspace from the test-stack page:
```
2.248.236.237 - - [03/Apr/2017:18:33:10 +0000] "POST /api/workspace/runtime?temporary=true HTTP/1.1" 200 -
2.248.236.237 - - [03/Apr/2017:18:33:10 +0000] "GET /davideveborn/test-wksp-s65d HTTP/1.1" 200 -
2.248.236.237 - - [03/Apr/2017:18:33:11 +0000] "GET /dashboard/assets/branding/loader.svg HTTP/1.1" 200 2649
2.248.236.237 - - [03/Apr/2017:18:33:11 +0000] "GET /api/ws HTTP/1.1" 101 -
2.248.236.237 - - [03/Apr/2017:18:33:11 +0000] "GET /_app/browserNotSupported.js HTTP/1.1" 200 3242
2.248.236.237 - - [03/Apr/2017:18:33:11 +0000] "GET /_app/_app.nocache.js HTTP/1.1" 200 7851
2.248.236.237 - - [03/Apr/2017:18:33:11 +0000] "GET /_app/IDE.css HTTP/1.1" 200 3870
2.248.236.237 - - [03/Apr/2017:18:33:11 +0000] "GET /_app/13E3E2D4729066EA46EE052BA1722B39.cache.js HTTP/1.1" 200 -
2.248.236.237 - - [03/Apr/2017:18:33:13 +0000] "GET /_app/font-awesome-4.5.0/css/font-awesome.min.css HTTP/1.1" 200 -
2.248.236.237 - - [03/Apr/2017:18:33:13 +0000] "GET /_app/ZeroClipboard.min.js HTTP/1.1" 200 -
2.248.236.237 - - [03/Apr/2017:18:33:13 +0000] "GET /api/preferences HTTP/1.1" 200 -
2.248.236.237 - - [03/Apr/2017:18:33:13 +0000] "GET /api/profile/ HTTP/1.1" 200 1006
2.248.236.237 - - [03/Apr/2017:18:33:13 +0000] "GET /api/workspace/davideveborn/test-wksp-s65d HTTP/1.1" 200 -
2.248.236.237 - - [03/Apr/2017:18:33:14 +0000] "GET /api/ws HTTP/1.1" 101 -
2.248.236.237 - - [03/Apr/2017:18:33:14 +0000] "GET /api/project-template/all HTTP/1.1" 200 -
2.248.236.237 - - [03/Apr/2017:18:33:15 +0000] "GET /_app/ZeroClipboard.swf?noCache=1491244394268 HTTP/1.1" 200 4036
2.248.236.237 - - [03/Apr/2017:18:33:15 +0000] "GET /_app/font-awesome-4.5.0/fonts/fontawesome-webfont.woff2?v=4.5.0 HTTP/1.1" 200 66624
2.248.236.237 - - [03/Apr/2017:18:33:15 +0000] "GET /_app/require.js HTTP/1.1" 200 -
2.248.236.237 - - [03/Apr/2017:18:33:15 +0000] "GET /api/bitbucket/endpoint HTTP/1.1" 200 -
2.248.236.237 - - [03/Apr/2017:18:33:15 +0000] "GET /_app/activity.js HTTP/1.1" 200 1870
2.248.236.237 - - [03/Apr/2017:18:33:16 +0000] "GET /_app/term/xterm.js HTTP/1.1" 200 -
2.248.236.237 - - [03/Apr/2017:18:33:42 +0000] "GET /api/workspace/workspace0vzhkaqv0hp9h3ww HTTP/1.1" 200 -
2.248.236.237 - - [03/Apr/2017:18:33:43 +0000] "GET /api/workspace/workspace0vzhkaqv0hp9h3ww/snapshot HTTP/1.1" 200 -
2.248.236.237 - - [03/Apr/2017:18:33:43 +0000] "PUT /api/preferences HTTP/1.1" 200 -
2.248.236.237 - - [03/Apr/2017:18:33:43 +0000] "GET /api/workspace HTTP/1.1" 500 -
2.248.236.237 - - [03/Apr/2017:18:34:16 +0000] "PUT /api/activity/workspace0vzhkaqv0hp9h3ww HTTP/1.1" 403 -
2.248.236.237 - - [03/Apr/2017:18:34:46 +0000] "PUT /api/activity/workspace0vzhkaqv0hp9h3ww HTTP/1.1" 403 -
2.248.236.237 - - [03/Apr/2017:18:34:51 +0000] "GET /api/workspace/workspace0vzhkaqv0hp9h3ww HTTP/1.1" 500 -
2.248.236.237 - - [03/Apr/2017:18:35:16 +0000] "PUT /api/activity/workspace0vzhkaqv0hp9h3ww HTTP/1.1" 403 -
2.248.236.237 - - [03/Apr/2017:18:35:38 +0000] "DELETE /api/workspace/workspace0vzhkaqv0hp9h3ww/runtime?create-snapshot=false HTTP/1.1" 500 -

```

**Comment by mshaposhnik** [comment] 2017-04-14 14:04
1st usecase have the same flow: create tmp ws, then it fails.
```
*.*.*.192 - - [18/Mar/2017:18:48:40 +0000] "GET /api/stack?maxItems=50 HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:48:40 +0000] "GET /api/agent HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:48:44 +0000] "POST /api/workspace/runtime?temporary=true HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:48:45 +0000] "GET /jlkonjl/test-wksp-1o1m HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:48:45 +0000] "GET /_app/browserNotSupported.js HTTP/1.1" 200 3242
*.*.*.192 - - [18/Mar/2017:18:48:45 +0000] "GET /_app/_app.nocache.js HTTP/1.1" 200 7851
*.*.*.192 - - [18/Mar/2017:18:48:45 +0000] "GET /_app/IDE.css HTTP/1.1" 200 3870
*.*.*.192 - - [18/Mar/2017:18:48:45 +0000] "GET /_app/F6B640B99E7CBB94CF87FF9702CB7F47.cache.js HTTP/1.1" 304 -
*.*.*.192 - - [18/Mar/2017:18:48:48 +0000] "GET /_app/font-awesome-4.5.0/css/font-awesome.min.css HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:48:49 +0000] "GET /_app/ZeroClipboard.min.js HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:48:50 +0000] "GET /api/preferences HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:48:51 +0000] "GET /api/profile/ HTTP/1.1" 200 1009
*.*.*.192 - - [18/Mar/2017:18:48:52 +0000] "GET /api/workspace/jlkonjl/test-wksp-1o1m HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:48:52 +0000] "GET /api/ws HTTP/1.1" 101 -
*.*.*.192 - - [18/Mar/2017:18:48:54 +0000] "GET /api/project-template/all HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:48:56 +0000] "GET /_app/ZeroClipboard.swf?noCache=1489862935252 HTTP/1.1" 200 4036
*.*.*.192 - - [18/Mar/2017:18:48:57 +0000] "GET /_app/font-awesome-4.5.0/fonts/fontawesome-webfont.woff2?v=4.5.0 HTTP/1.1" 200 66624
*.*.*.192 - - [18/Mar/2017:18:48:57 +0000] "GET /api/workspace/workspace7yt2h17zokh4bd0x HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:48:57 +0000] "GET /api/bitbucket/endpoint HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:48:57 +0000] "GET /_app/require.js HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:48:57 +0000] "GET /_app/activity.js HTTP/1.1" 200 1870
*.*.*.192 - - [18/Mar/2017:18:48:58 +0000] "GET /_app/term/xterm.js HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:52:56 +0000] "GET /api/workspace/workspace7yt2h17zokh4bd0x HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:52:58 +0000] "GET /api/workspace/workspace7yt2h17zokh4bd0x HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:53:00 +0000] "GET /api/workspace/workspace7yt2h17zokh4bd0x HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:53:00 +0000] "GET /api/workspace/workspace7yt2h17zokh4bd0x/snapshot HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:53:00 +0000] "PUT /api/preferences HTTP/1.1" 200 -
*.*.*.192 - - [18/Mar/2017:18:53:01 +0000] "GET /api/workspace HTTP/1.1" 500 -
*.*.*.192 - - [18/Mar/2017:18:53:49 +0000] "GET /api/workspace/workspace7yt2h17zokh4bd0x HTTP/1.1" 500 -
*.*.*.192 - - [18/Mar/2017:18:53:57 +0000] "PUT /api/activity/workspace7yt2h17zokh4bd0x HTTP/1.1" 403 -
*.*.*.192 - - [18/Mar/2017:18:55:28 +0000] "PUT /api/activity/workspace7yt2h17zokh4bd0x HTTP/1.1" 403 -
*.*.*.192 - - [18/Mar/2017:18:58:53 +0000] "DELETE /api/workspace/workspace7yt2h17zokh4bd0x/runtime?create-snapshot=false HTTP/1.1" 500 -
*.*.*.192 - - [18/Mar/2017:19:04:47 +0000] "PUT /api/stack/stackek4er0kc8netg1ap HTTP/1.1" 200 -
```

**Comment by mshaposhnik** [comment] 2017-04-20 08:03
Since we can not reproduce issue manually, and since 5.5.0 we did a lot of fixes to improve DB performance and integrity, we're closing issue right now, but continue to monitor if similar  errors are happened.

**Closed by mshaposhnik** 2017-04-20 08:03 UTC
Labels: kind/bug, kind/planning, severity/P1, sprint/current-sprint, status/open-for-dev, team/production
