### ISSUE TITLE
Configure Source Directories in Complex Projects

### ISSUE THREAD

**Issue by bobpaige** [codenvy/codenvy#1045] opened 2016-10-27 12:06 UTC
Related to (https://github.com/codenvy/codenvy/issues/1036) I need a way to configure multiple source directories in a complicated project.

**Reproduction Steps:**

1. import a project from Git
1a. specify one (the wizard only asks for one) source directory
2. manually set all source paths through the Configure Classpath dialog (all 12-16 of them)
3. create a new workspace and import the same (or similar) project
4. repeat step 2

**Expected behavior:**

Support for Gradle would be awesome, but even if we just have the ability to generate a ".classpath" file like we do with Eclipse to configure all the source directories and libraries, that would be great. Much better than manually specifying everything.

Alternately, make me do it once but allow me to import this configuration as part of creating a new project, from some recipe file or something.

**Observed behavior:**

Every time I import a project, I have to manually set all the source paths and libraries.

**Codenvy version:** 5.0.0-M5
**OS and version:** [Enter OS name and version here]

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: [Yes / No]
Problem can be reliably reproduced: [Yes / No - it's random]

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.

**Comment by TylerJewell** [comment] 2016-10-27 12:43
You can work around this - it's ugly.  But there is a ".che" hidden directory in the project and within the workspace, which has the references to the classpath.  You can generate a custom stack that has these pre-configured, and when the workspace is created from the image, it would have the configuration that you are seeking.

**Comment by bobpaige** [comment] 2016-10-27 12:53
I will try this, but as I recall when I tried editing this file (or generating this file) when I trialed Eclipse Che, the changes didn't take. I will let you know.

Also, not your issue (I'm working with my IT) but the default Java workspace doesn't include any commandline editing tools, and Codenvy won't show them to me, so I'm effectively locked out of them for the moment :)

**Comment by TylerJewell** [comment] 2016-10-27 12:54
We are in a constant fight with image bloat - so there is always a tendency to want to add in things like emacs into the default image, but they start to get to be really large.

**Comment by bobpaige** [comment] 2016-10-27 13:00
Re: Image bloat - fortunately it is something we can control by defining our own images, right? We just need to be careful with what we add.

Re: .codenvy/classpath - I just tried copying the classpath file from one project to another (I cloned the same repo twice so I could compare them). Codenvy doesn't see my changes (doesn't realize I've added new source directories). Even when I "Configure classpath" it doesn't show my changes. Maybe it caches it in memory? I tried "Refresh project" but that didn't re-read it either.

Will try restarting the workspace.

**Comment by bobpaige** [comment] 2016-10-27 13:19
Confirmed that restarting the workspace does not force .codenvy/classpath to be re-read. Are you saving another copy somewhere else?

**Comment by gazarenkov** [comment] 2016-10-27 13:32
@bobpaige 
Your expectations are fair enough.
The problem is that we have classpath gitignored by default (we tend to rethink this policy).
Meantime as a workaround try to force adding  .codenvy/classpath to git index using -f option.
HTH

**Comment by bobpaige** [comment] 2016-10-27 13:35
How does gitignoring the classpath file affect whether you see it or not? I'm modifying this in-place, not committing.

I would assume I will see the same behavior whether the sources are saved in git or not, unless you are doing something behind the scenes.

**Comment by gazarenkov** [comment] 2016-10-27 13:39
It does not affect if you can see the file or not, it affects if you are able to commit/push it and then take it after next clone (import).

**Comment by bobpaige** [comment] 2016-10-27 13:41
Ok. The issue is I updated the file in my project, hoping to achieve the same results as manually adding source paths through the Configure Classpath dialog, but Codenvy did not see the changes.

**Comment by gazarenkov** [comment] 2016-10-27 13:48
Your steps:

- import a project from Git 1a. specify one (the wizard only asks for one) source directory
- manually set all source paths through the Configure Classpath dialog (all 12-16 of them)

To make next step work you have to add .codenvy/classpath to git index using -f option and push the changes. This way you save it file, otherwise it will be generated w/o your changes.

- create a new workspace and import the same (or similar) project

**Comment by bobpaige** [comment] 2016-10-27 13:52
So the only way to not have to manually configure my classpath (which may change over time, though not often) is to commit tool-specific configuration files to my git repository. I'm sorry, but I don't actually like this solution. I will try it to see if it works, but I dislike putting project configuration files in source control as developers may modify them inconsistently.

My preference would be to update (or generate) whatever configuration files Codenvy requires. We do that very successfully with Eclipse now and I was hoping we could do the same here. 

Apparently Codenvy has some hidden files/configuration we can't access?

**Comment by vparfonov** [comment] 2016-10-27 14:15
@bobpaige  Main Menu -> Project - > Show/Hide Hidden Files

**Comment by gazarenkov** [comment] 2016-10-27 14:35
In a case if Project Type considers external build manager we would tend to use its description and generate classpath file (just like Eclipse does in this case I think), like for Maven project we use pom.xml and if we support Gradle we would use *.gradle build files etc.
For "bare" Java project we generate classpath file using information user input in the wizard (source folders, libs).
Apparently to have exactly the same classpath for cloned instance you have to save changes of your metainfo source files to git repository. I.e. changes of pom.xml for maven or classpath for bare Java project should be committed and pushed remotely to make it work (see my previous comments about workaround I propose). Yes we will think about how to make it more obvious.
Thanks

**Comment by bobpaige** [comment] 2016-10-27 15:18
Thanks for the response. Native support of Gradle, or even some well-defined process for generating a classpath configuration would be great.

In the short term, I think I found an option for Gradle to generate .pom files so we can masquerade as a maven project. Maybe that will work better with Codenvy in the short term.

**Closed** 2016-10-27 19:43 UTC
Labels: kind/question

**Comment by pwachira** [comment] 2017-10-31 01:25
Configure classpath dialog is not enabled - the add folder or add jar options are not selectable...
