### ISSUE TITLE
Workspace has corrupted

### ISSUE THREAD

**Issue by lidoma** [codenvy/codenvy#443] opened 2016-07-24 09:08 UTC
Today when i start my workspace, got this error:
![untitled](https://cloud.githubusercontent.com/assets/2203739/17082928/c19e64cc-51a3-11e6-9a93-435d460259e6.png)

Can not start container anyway!?

**Comment by TylerJewell** [comment] 2016-07-24 13:02
This looked like a temporary swarm issue earlier today.  The systems were automatically restarted.  Please log into the product and restart your workspace.

**Comment by lidoma** [comment] 2016-07-24 13:28
I try again but error is still there.

**Comment by bmicklea** [comment] 2016-07-26 13:06
A couple of questions to help in diagnosis:

- Is this using a default stack project?  Or a custom stack?
- How much memory was granted to the workspace?
- Can you see if there are any errors in the Chrome dev console?

**Comment by lidoma** [comment] 2016-07-26 13:17
Answers:
- Yes. A default stack from codenvy/php:ubuntu.
- The workspace has 3 GB memory.
- No. There is not any errors in the Chrome dev console.

**Comment by eivantsov** [comment] 2016-07-27 10:41
@lidoma can you create a new workspace rather than restart an existing one?

I have just checked php stack on beta - no issues found.

**Comment by lidoma** [comment] 2016-07-27 11:05
Yes, I can.
Last time I ran workspace successfully, I download some archive files around 5 GB in /projects folder. Can this action be the reason of workspace corruption?
I think there is a problem with retrieving projects files.

**Comment by eivantsov** [comment] 2016-07-28 05:44
@lidoma yes, this is most certainly the cause. Probably rsync failed or smth similar happened.

**Comment by lidoma** [comment] 2016-08-03 05:31
The Codenvy team, is there any luck to recover my workspace?

**Comment by eivantsov** [comment] 2017-02-20 08:02
@lidoma hosting huge file will inevitably result in workspace start failures. Codenvy isn't a hosting service. I am closing the issue.

**Closed by eivantsov** 2017-02-20 08:02 UTC
Labels: kind/question
