### ISSUE TITLE
I can't access my github account from my IDE

### ISSUE THREAD

**Issue by juan19xx** [codenvy/codenvy#2203] opened 2017-05-16 18:01 UTC
Hi,
Today I wanted to import a project from github but I couldn't do it.

Reproduction Steps:
I went to workspace, import project, select github, then I clicked on load repo and nothing happened, usually when I do that I see a new window asking me for the repo I want to load, but today I couldn't do that.
I also checked the profile->preferences->vcs window so I can put my github data there but it loads forever as the other option.
I'm using codenvy 5.10.0.

Thanks, hope you can help me.

**Comment by mloetkemann** [comment] 2017-05-16 20:07
Hi,

I have similar problems. I was trying to import a git project from Bitbucket but it failed. Also every git command to a remote repository is failing. Yesterday it was working.

Return of git commands: "unknown host"

Version: 5.10.0-SaaS

**Comment by eivantsov** [comment] 2017-05-17 06:22
Investigating. There are connectivity issues on codenvy.io

**Comment by eivantsov** [comment] 2017-05-17 06:36
@mloetkemann @juan19xx can you try it again? Looks like the issue is fixed now.

**Comment by mloetkemann** [comment] 2017-05-17 06:41
It is working for me. Thanks!

**Closed** 2017-05-17 06:58 UTC
Labels: kind/question

**Comment by juan19xx** [comment] 2017-05-17 14:34
It's working again thank you
