### ISSUE TITLE
Sometimes machine.ws_agent.run_command can't execute properly

### ISSUE THREAD

**Issue by vkuznyetsov** [codenvy/codenvy#405] opened 2016-07-19 11:06 UTC
Sometimes when we starting dev machine exec which extract and launch ws agent does not work. there is no any error or useful message and as result we have running docker container without ws agent inside. 
as a workaround we've added sleep 5 sec to command due to assumption that mount point inside of a docker container is not available immediately after starting container.
machine.ws_agent.run_command=sleep 5 && rm -rf ~/che && mkdir -p ~/che && unzip -qq /mnt/che/ws-agent.zip -d ~/che/ws-agent && ~/che/ws-agent/bin/catalina.sh run
But it seems that it's not solved our problem it is still actual.

**Comment by vkuznyetsov** [comment] 2016-07-19 11:07
now we've changed command to:

`machine.ws_agent.run_command=sleep 5 && mkdir -p ~/che && rm -rf ~/che/* && unzip -q /mnt/che/ws-agent.zip -d ~/che/ws-agent && ~/che/ws-agent/bin/catalina.sh run`

and on my environment it works again, but I'm sure this wasn't fixed issue.

**Comment by mmorhun** [comment] 2016-07-26 08:36
Cannot reproduce it. It seems, that mounted volume wasn't ready for write after mounting and this was fixed by docker update.

**Comment by JamesDrummond** [comment] 2016-07-28 21:51
Does this need a status/info-needed?

**Closed** 2016-07-29 13:04 UTC
Labels: kind/bug, sprint/current-sprint, team/enterprise
