### ISSUE TITLE
Click on element in a project explorer jumps to the top of a tree

### ISSUE THREAD

**Issue by ghenadiibatalski** [codenvy/codenvy#1488] opened 2017-01-05 18:09 UTC
After scrolling down to a desired position in a project explorer's object tree, i click on any element and the cursor jumps to top of a tree.

**Reproduction Steps:**

Open a project with larger structure
Scroll some pages down
Click on any element

**Expected behavior:**
Default reaction on a click: either the folder expands or a file opens in an editor view.

**Observed behavior:**

Cursor jumps up to top of a tree, file doen't open

**Codenvy version:** 5.0.0-M8 and 5.0.0-nightly
**OS and version:** Client: Windows 10, Server: Ubuntu 16.10 / Azure Codenvy Team
**Browser version:** Chrome 55.0.2883.87, Firefox 50.1.0

**Other questions:**
Problem happens at codenvy.io or with the installed Codenvy Enterprise?: Yes (Dockerized Installation, Azure Installation)
Problem can be reliably reproduced: Yes, always

**Comment by eivantsov** [comment] 2017-01-06 08:24
@ghenadiibatalski I cannot reproduce this one on codenvy.io. Can you perhaps share more details on how to reproduce? I Opened a project with files and folders enough to scroll, then scrolled down to the top and clicked on a file to open. The file opened.

**Comment by ghenadiibatalski** [comment] 2017-01-06 13:38
just see the animation attached. It is recorded just now on Ubuntu desktop, Chromium and codenvy.io If it helps, the project was initially created from the nodejs project template but the node_modules folder is generated by `npm install`. 
![anim](https://cloud.githubusercontent.com/assets/24528146/21719288/33eabd7c-d41d-11e6-83e3-6ee5a99daa10.gif)

**Comment by eivantsov** [comment] 2017-01-06 13:40
@ghenadiibatalski thanks

**Comment by eivantsov** [comment] 2017-01-06 14:37
Just tried it with an Angular project. Cannot reproduce.

**Comment by ghenadiibatalski** [comment] 2017-01-06 17:56
just tried it with a hello-world nodejs project and have got the same behaviour.... Open folder nodejs-hello-world->node_modules->express->node_modules , scroll a page down with the mouse and click with the mouse on any folder. The cursor jumps to the top.

If i use a keyboard  for tree navigation, then the mouse works sporadically.

**Comment by TylerJewell** [comment] 2017-01-06 18:26
Could this be a weird CSS rendering issue that is unique to Chrome on Ubuntu that somehow doesn't exist with other Chrome versions?

**Comment by ghenadiibatalski** [comment] 2017-01-06 18:40
i don't think. Same issue initially on Win 10 FF and Chrome both latest versions and Codenvy On-Prem.

**Comment by TylerJewell** [comment] 2017-01-06 18:42
Project type select can affect the behavior of the project tree.  I don't see any specification of PT in your reproduction steps.  Did you leave the PT as blank or did you set it to one of the types in the wizard?  If you set the project to a javac project type does the issue still exist (I know your project is not java - but curious).

**Comment by ghenadiibatalski** [comment] 2017-01-06 19:30
same behaviour for java project cloned from github just now

**Comment by TylerJewell** [comment] 2017-01-06 19:34
Just to be explicit - did you go into the Project Type... selector in the Project menu and change the PT?  I want to be sure that it's a PT thing and not just the clone of code.

**Comment by ghenadiibatalski** [comment] 2017-01-06 19:37
same

**Comment by TylerJewell** [comment] 2017-01-06 19:40
Well, huh.  Does it happen for you on this particular server (this is 5.0.0 release candidate which has another 150 issues resolved in it).  https://codenvy-stg.com/site/login?redirect_url=https%3A%2F%2Fcodenvy-stg.com%2F

**Comment by ghenadiibatalski** [comment] 2017-01-06 19:59
same here, scroll view jumps to the first page of the tree, but the cursor is set to the clicked node. so i can navigate further with keys from clicked element.

**Comment by TylerJewell** [comment] 2017-01-06 21:16
I am calling it a bug for now and adding in a development team, though only for them to try and offer some additional ideas on what we can activate to try and make this reproducible.

**Comment by JamesDrummond** [comment] 2017-01-10 18:03
Here are some screen captures. You will notice some items don't cause this jump at certain times depending on state of project explorer tree.

Chrome Version 55.0.2883.87 m (64-bit)
![issue2](https://cloud.githubusercontent.com/assets/20580888/21817903/71f43876-d72b-11e6-9915-e048c36c0548.gif)

This is also happening in firefox 50.1.0 windows 10.

![issue](https://cloud.githubusercontent.com/assets/20580888/21818175/6f230a9a-d72c-11e6-9410-3bb73a998172.gif)

**Comment by vzhukovskii** [comment] 2017-01-11 08:27
I'll take a look on this issue asap.

**Comment by natthawute** [comment] 2017-01-17 05:10
I got the same issue on Chrome and Firefox (macOS sierra) but it seems to be fine on Safari.

**Comment by vzhukovskii** [comment] 2017-01-17 08:02
Confirm. This is a bug, trying to solve it.

**Comment by vzhukovskii** [comment] 2017-01-17 10:39
Issue related to `che`, not `codenvy`. So there new issue was created with attached pull request.

https://github.com/eclipse/che/issues/3762 Issue
https://github.com/eclipse/che/pull/3763 PR

**Closed** 2017-01-17 16:52 UTC
Labels: kind/bug, kind/question, severity/P2, team/ide

**Comment by KGer80** [comment] 2020-03-28 17:07
edited: removing my false report, sry

issue occured at me probably since one of my keyboard key was stuck
