### ISSUE TITLE
FileWatcherService error when importing git project

### ISSUE THREAD

**Issue by alespstemc** [codenvy/codenvy#2153] opened 2017-05-02 12:00 UTC
I'm trying to import a project via git to my workspace, but, when i do so, it give me a bunch of errors and the operation doesn't complete.

**Reproduction Steps:**

1. Click on "import project"
2. Fill the fields with ssh address
3. Click "import"

the following message appears on the console:

[STDOUT] 2017-05-02 11:36:26,787[nio-4401-exec-4]  [INFO ] [a.c.w.i.BasicWebSocketEndpoint 49]   - Web socket session opened
[STDOUT] 2017-05-02 11:36:26,787[nio-4401-exec-4]  [INFO ] [a.c.w.i.BasicWebSocketEndpoint 50]   - Endpoint: 734840614
[STDOUT] 2017/05/02 11:36:27 A new channel with id 'channel-1' successfully opened
[STDOUT] 2017/05/02 11:36:27 Start new terminal.
[STDOUT] 2017-05-02 11:46:19,528[eWatcherService]  [ERROR] [oggingUncaughtExceptionHandler 29]   - Runtime exception caught in thread FileWatcherService. Message: null
[STDOUT] java.lang.NullPointerException: null
[STDOUT] 	at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)
[STDOUT] 	at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)
[STDOUT] 	at org.eclipse.che.api.vfs.watcher.FileWatcherService.resetAndRemove(FileWatcherService.java:321)
[STDOUT] 	at org.eclipse.che.api.vfs.watcher.FileWatcherService.run(FileWatcherService.java:282)
[STDOUT] 	at org.eclipse.che.api.vfs.watcher.FileWatcherService$$Lambda$13/482988911.run(Unknown Source)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[STDOUT] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[STDOUT] 	at java.lang.Thread.run(Thread.java:745)
[STDOUT] 2017-05-02 11:46:22,694[ted-scheduler-1]  [ERROR] [o.e.c.a.v.w.FileWatcherService 199]  - Can't register dir /projects/manutencao/.git in file watch service
[STDOUT] java.nio.file.NoSuchFileException: /projects/manutencao/.git
[STDOUT] 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[STDOUT] 	at sun.nio.fs.UnixException.asIOException(UnixException.java:111)
[STDOUT] 	at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:246)
[STDOUT] 	at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
[STDOUT] 	at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329)
[STDOUT] 	at java.lang.Thread.run(Thread.java:745)
[ERROR] Command output read timeout is reached. Process is still running and has id 24 inside machine
[ERROR] Command output read timeout is reached. Process is still running and has id 208 inside machine

**Codenvy version:** 
5.9.1

**OS and version:**
Windows 7 32-bit PT-BR

**Comment by 20avva** [comment] 2017-05-02 12:45
Assuming you are importing from Github, follow these steps:

1. Click `Workspace`
2. Click `Import Project`
3. Click `github` under `Source Control`
4. Click `Load Repo` at the bottom of that menu
5. Codenvy may ask to upload a ssh key on your behalf, Click yes
6. Click on the Repo you want to import
7. Click the blue import button at the bottom of the import dialog

**Comment by 20avva** [comment] 2017-05-02 12:48
Side note: While you can clone, push, and pull using ssh through the IDE, you cannot use it from the terminal (eg. typing the commands `git add . && git commit -m "foo" && git push`) you will have to set up a separate ssh key for the terminal, doing it as you would [here](https://help.github.com/articles/connecting-to-github-with-ssh/). The terminal OS is Ubuntu.

**Comment by eivantsov** [comment] 2017-05-12 13:07
@20avva can you reliably reproduce it with any repo you clone?

**Comment by 20avva** [comment] 2017-05-13 23:36
Yes, if you clone a repo over https via the terminal, then use Che's Git plugin (that is what it is called right?) to push to github, it would not allow you to do so. I will post a screen shot in a minute...

**Comment by 20avva** [comment] 2017-05-13 23:42
@eivantsov or you can try it yourself (my workspace isn't starting but I think it is a problem from my end) by:

* Launch a workspace
* Use the terminal to `git clone https://github.com/user/repo`
* Make a change to any file
* Right click on the project's root folder
* Click `Git > Add to index`
* Click `Git > Commit selected (or equiv.)`
* Click `Git > Push`
* The workspace should fail to push
* Now, delete the project
* Click `Import Project > GITHUB > (scroll down) Load Repo`
* Codenvy might ask you to upload a SSH key on your behalf
* Import any project of yours
* Make a change
* Right click on the root project folder
* Add to index, commit and click push
* It should work now.

**Comment by eivantsov** [comment] 2017-05-14 10:40
@20avva git in the workspace terminal and UI git are two different systems. To be able to push to remote repos, you should use UI git, set up SSH keys etc.

**Comment by 20avva** [comment] 2017-05-15 14:31
@eivantsov that's what I thought 👍

**Comment by eivantsov** [comment] 2017-05-24 08:26
Closing this issue as a duplicate of https://github.com/eclipse/che/issues/5169
@20avva you are welcome to follow it

**Closed by eivantsov** 2017-05-24 08:26 UTC
Labels: kind/question
