### ISSUE TITLE
FIND command will not scal

### ISSUE THREAD

**Issue by jcoonrod** [codenvy/codenvy#500] opened 2016-08-01 18:41 UTC
** If you are a Codenvy customer or have a trial license please file your issues with Support through email. GitHub issues do not have a response SLA.**

[Short description of problem here]
Issuing a ctrl-F command will not search across multiple php files

Reproduction Steps:

[First Step]
1. Have a project of php files
[Second Step]
2. Hit ctrl-F and select the scope root and some text to find that exists in those files
[Other Steps...]
Expected behavior:
It would list the instances of that content.

Observed behavior:
It says "Find occurences of <text>: (0 occurrence)

Codenvy version: 4.5.1
OS and version: ChromeOS 51.0.2704.106

Additional information:

Problem only started happening recently, didn't happen in an older version of Codenvy: [ No]
Problem can be reliably reproduced: [Yes]

**Comment by eivantsov** [comment] 2016-08-02 06:32
Duplicate of https://github.com/eclipse/che/issues/1952

**Closed by eivantsov** 2016-08-02 06:32 UTC
