### ISSUE TITLE
Strange warning about the age of cli

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1235] opened 2016-11-28 08:07 UTC
Time between pull and start is less when 5 seconds.
```
[sj@sj-i7:~]$ docker pull codenvy/cli:nightly
nightly: Pulling from codenvy/cli
3690ec4760f9: Already exists
7051054843ad: Pull complete
7f7cf4fed7d8: Pull complete
dab5fe448713: Pull complete
fdc0fc307ee8: Pull complete
db1d8ac5eade: Pull complete
7d75ce5665bc: Pull complete
38dd061b3001: Pull complete
Digest: sha256:73a348c7a0267466be66f00f1a419f4976d044026862c64527387ec98f998bcc
Status: Downloaded newer image for codenvy/cli:nightly
[sj@sj-i7:~]$ codenvy start --pull
INFO: (codenvy cli): Loading cli...
WARN: Your local codenvy/cli:nightly image is older than the version on DockerHub.
WARN: Run 'docker pull codenvy/cli:nightly' to update your CLI.
INFO: (codenvy cli): Checking registry for version 'nightly' images
INFO: (codenvy download): Pulling image codenvy/socat:1.7.3.1
```

**Comment by TylerJewell** [comment] 2016-11-28 13:06
Not a bug.

We discussed this in slack as a possible issue.  It cannot be fixed.

**Comment by TylerJewell** [comment] 2016-11-30 16:44
Seems this logic is returning '0' when it should return '1'
```
 if $(less_than ${LOCAL_CREATION_DATE:8:2} ${REMOTE_CREATION_DATE:8:2}); then
      warning "Your local ${CHE_IMAGE_FULLNAME} image is older than the version on DockerHub."
      warning "Run 'docker pull ${CHE_IMAGE_FULLNAME}' to update your CLI."
fi
```

**Comment by benoitf** [comment] 2016-12-12 17:42
PR is there https://github.com/eclipse/che/pull/3357

**Comment by benoitf** [comment] 2016-12-13 08:36
Fixed by https://github.com/eclipse/che/pull/3357
please reopen if not working

**Comment by benoitf** [comment] 2016-12-13 10:42
it's not fxed as date are not the same date
created date vs published date

**Comment by TylerJewell** [comment] 2016-12-13 14:28
@benoitf - I don't think we can solve that problem.  I think the only thing we can do is to check if the created date is >2 days older than the published date, and then we know we have a nightly issue.  So I think we had that logic - but if you can add that back in, then we can close this.

**Comment by benoitf** [comment] 2016-12-16 07:27
Fixed

**Closed by benoitf** 2016-12-16 07:27 UTC
Labels: kind/bug, status/in-progress
