### ISSUE TITLE
beta.codenvy.com Share function does not work

### ISSUE THREAD

**Issue by gwynnbleiidd** [codenvy/codenvy#881] opened 2016-09-30 13:49 UTC
The problem as #700 

**Reproduction Steps:**

Create a new workspace
Go into the workspace settings
Click share
Click add member
Try and enter an email address
It is not possible to click share, even when removing disabled from the button in chrome dev tools, the user is not added.

**Expected behavior:**

Chrome Console:
```
vendor-dbdc29a564.js:33838 TypeError: Cannot read property 'location' of undefined
    at e.value (app-39125182a1.js:11370)
    at e.value (app-39125182a1.js:10995)
    at e.value (app-39125182a1.js:11652)
    at fn (eval at compile (vendor-dbdc29a564.js:34683), <anonymous>:4:292)
    at vendor-dbdc29a564.js:110972
    at h.$eval (vendor-dbdc29a564.js:37370)
    at h.$apply (vendor-dbdc29a564.js:37470)
    at HTMLButtonElement.<anonymous> (vendor-dbdc29a564.js:110971)
    at HTMLButtonElement.dispatch (vendor-dbdc29a564.js:16353)
    at HTMLButtonElement.g.handle (vendor-dbdc29a564.js:16161)(anonymous function) @ vendor-dbdc29a564.js:33838(anonymous function) @ vendor-dbdc29a564.js:30610$apply @ vendor-dbdc29a564.js:37475(anonymous function) @ vendor-dbdc29a564.js:110971dispatch @ vendor-dbdc29a564.js:16353g.handle @ vendor-dbdc29a564.js:16161
```

**Codenvy version:** 4.7
**OS and version:** beta.codenvy.com

**Diagnostic bundle**
[report.zip](https://github.com/codenvy/codenvy/files/503091/report.zip)

**Comment by ddementieva** [comment] 2016-09-30 14:15
@gwynnbleiidd We have the issue registered on that. You can track it with https://github.com/codenvy/codenvy/issues/725

**Comment by bmicklea** [comment] 2016-10-10 12:39
Closing as a duplicate of #725

**Closed by bmicklea** 2016-10-10 12:39 UTC
