### ISSUE TITLE
Exposed port sometimes not mapped to host

### ISSUE THREAD

**Issue by xbtsw** [codenvy/codenvy#1579] opened 2017-01-21 00:58 UTC
I am testing with setting up a stack on codenvy.io however the "perspective switcher" is sometimes missing. 
![image](https://cloud.githubusercontent.com/assets/4098537/22170300/f2868342-df30-11e6-9d02-116171c98622.png)
For the exact same workspace, it was here yesterday however not there for today. I tried re-login, refresh, clear browser cache, restart workspace without snapshot nothing helped.

When this happens, checking from the "workspace" doesn't help either:
![image](https://cloud.githubusercontent.com/assets/4098537/22170326/335d441e-df31-11e6-967c-edc03c57a74d.png)

The codenvy version according to dashboard is 5.1.0

**Comment by TylerJewell** [comment] 2017-01-21 01:01
The perspective switcher in the IDE has been removed and all servers are now in the user dashboard only.  I see them there.  You can see more details on that aspect here - https://github.com/codenvy/codenvy/issues/1563.

Can you give us some more details about the workspace stack that you are exposing?  Are you sure that there is an EXPOSE entry in that Dockerfile so that the port gets properly mapped?

Last night we did an upgrade to 5.1.1 and in that upgrade was some workarounds to a Docker daemon bug that was hurting how workspace snapshots are being created.  So I wonder if this may be an issue.  Could you create an entirely new workspace from the stack and does it not expose the proper port?

**Comment by xbtsw** [comment] 2017-01-21 01:07
Thanks for the fast reply.

I am pretty sure the EXPOSE entry is there. The same workspace actually works yesterday.

To validate, I just created a new workspace using the ready-to-use node.js stack, have it running but still unable to see the port being mapped on the dashboard:
![image](https://cloud.githubusercontent.com/assets/4098537/22170491/ec0ce1c6-df32-11e6-8c1e-00c5b539f8ef.png)

**Comment by TylerJewell** [comment] 2017-01-21 01:08
Are you in a position where you can share the stack recipe and the Dockerfile that makes up your image?

**Comment by xbtsw** [comment] 2017-01-21 01:12
For the last post, I simply used the officially provided Node stack to create a new workspace, this one:

![image](https://cloud.githubusercontent.com/assets/4098537/22170535/a3370674-df33-11e6-8f9b-13af40332823.png)

**Comment by TylerJewell** [comment] 2017-01-21 01:17
Ok - they are all properly exposed.  That image maps to this Dockerfile: https://github.com/eclipse/che-dockerfiles/blob/master/recipes/node/latest/Dockerfile

Once the workspace starts, are you starting a Node server inside the workspace that then binds to one of these ports: https://github.com/eclipse/che-dockerfiles/blob/master/recipes/node/latest/Dockerfile#L44.  Once you start a Node server that is bound to one of those ports, then we would detect the external hostname and port that it is mapped to.

**Comment by xbtsw** [comment] 2017-01-21 01:47
I tried with a "hello world" express server and have it running, however the port 5000 is still not showing mapped on dashboard
![image](https://cloud.githubusercontent.com/assets/4098537/22170868/72658728-df38-11e6-8ed2-c72eaeb67af2.png)

**Comment by TylerJewell** [comment] 2017-01-21 14:48
@stevanlm @ashumilova - I see that this server was launched in the terminal.  If you launch the server with a preview URL from within a command does that change this?  We may require the extra preview to be calculated using macros for it to be registered properly.

**Comment by xbtsw** [comment] 2017-01-21 16:51
When I set up a command like so:
![image](https://cloud.githubusercontent.com/assets/4098537/22176016/e4007bd6-dfb5-11e6-8da2-2ac620b5eb35.png)

Running it will give me the mapped port in terminal:
![image](https://cloud.githubusercontent.com/assets/4098537/22176022/003a5024-dfb6-11e6-83f3-9712d0387b57.png)

While the dashboard still not display the mapping:
![image](https://cloud.githubusercontent.com/assets/4098537/22176030/37982384-dfb6-11e6-8e78-3868d91f5e50.png)

However the mapped port works.

though I am new to codenvy, I don't think running a server or invoking the marco was the required to have the port mapped before the update....if so, how do we deal with the pre-made containers that have the CMD running the server, for example https://hub.docker.com/_/mongo-express/

**Comment by TylerJewell** [comment] 2017-01-21 17:02
It will be good to get some of the docker experts to comment here.  I think as an enhancement request in the future we should be able to interrogate your workspace containers for a list of their exposed ports and then to see if any of them have been mapped and bound with a running server.

In the meantime, are you in a position to have your users select a custom template / project sample?  That template can come with commands built in that have previews in them.   You can also use codenvys factory functionality to auto launch workspaces and launch commands inside.  So your users would see the workspace load and command launched.

**Comment by xbtsw** [comment] 2017-01-21 17:25
I feel that the mapped ports are always mapped after the workspace is up - no matter if a server is running or marco is invoked. But currently the only way to know the mapped URL is to invoke a marco, because the Ops perspective is gone and dashboard is not displaying the mapping (if I remembered correctly, dashboard was displaying them before).

In the meantime, I guess I need to resort to this adhoc Ops perspective:
![image](https://cloud.githubusercontent.com/assets/4098537/22176272/8e72dca8-dfbb-11e6-94d4-dfab92378db4.png)

**Comment by TylerJewell** [comment] 2017-01-21 17:28
@slemeur - will you study this issue and make some recommendations?  I agree with @xbtsw point that if our workspace containers already are aware of the ephemeral port for anything exposed, whether the server is running or not, then we should be displaying all of those ephemeral ports in the servers list.

So the scenario is:
1. EXPOSED ports exist in recipe or Dockerfile
2. Server may or may not be running and bound to one of those ports
3. UD should display all of the IP / port mappings for each exposed port
4. We would probably interrogate the docker container to gain this info

**Comment by gazarenkov** [comment] 2017-01-22 08:52
No, running a server is not required.
Mapping should be performed for all EXPOSED.

I think we have bug in server resolving.
You can see it if you declare your server (BTW always recommended to have static reference) in UD: Runtimes -> DEV-MACHINE -> Servers add for example:
Reference: node
Port: 5000

then start workspace and back there you will see something like:
`node 5000 http http://node1.codenvy.io:40187`
which is not correct, compare with correct one  (added by Agent):
`wsagent 4401 https https://codenvy.io/40190_node1.codenvy.io/api`

where URL is transformed to suit codenvy.io infrastructure.

**Comment by TylerJewell** [comment] 2017-01-22 16:32
I am upgrading the severity level based upon Gennady's statement and reclassifying as a bug.

**Comment by gazarenkov** [comment] 2017-01-22 18:00
I think I forgot about some implementation details, Alex just reminded me that we have not considered this transformation for other than wsagent (and terminal) servers.
It is not very good but making "any" server URL task does not have fast and reliable solution.
And, both format are workable as for codenvy.io.
So, I do not think it can be qualified as a bug.

**Comment by TylerJewell** [comment] 2017-01-22 18:02
I think the issue is that the end user reasonably expects this functionality to be there. So while Alex says that it's behaving to specification, the work probably should not have been merged without the full implementation for all servers.  So from end user point of view, it's a bug.

**Comment by gazarenkov** [comment] 2017-01-22 18:14
Specification does not matter. 
Everyone agree that having unified URL is better, but it is not easy to solve. 
We have this implementation for a long time.
What "work to merge" you mean?

**Comment by TylerJewell** [comment] 2017-01-22 18:17
I do not know what a unified URL is.

The end user point of view is:
1. We previously had an operations view
2. It seems that the operations perspective that gave the IP address + ephemeral port for all exposed ports and servers whether they were running or not.
3. And the new UD view is not displaying the same information - that some information is missing vs. what was there previously.

So if there is a gap - then that perception from end user is that it's a step backwards.

**Comment by gazarenkov** [comment] 2017-01-22 19:07
Ah, you mean that UD does not show address? (sorry it was not that obvious to me)

Yes, it is UD issue, it should display address (which contain ephemeral port) and there is other problem - the protocol has defaulted "http" which is not correct in generic case.

**Comment by xbtsw** [comment] 2017-01-22 20:01
This was indeed a blocking issue for me since accessing the mapped port is the only way to test the application during development. 

After @TylerJewell pointed a way to get the mapped ports. I continue with my testing to create a custom stack, here's the compose file I used:
```
services:
  web:
    image: "eclipse/node"
    expose: 
      - 5000
  mongo:
    image: "mongo"
  mongo-admin:
    image: "mongo-express"
    expose: 
      - 8081
```
`eclipse/node` has [dockerfile here](https://github.com/eclipse/che-dockerfiles/blob/master/recipes/node/latest/Dockerfile), which exposed port 3000, 5000, 9000.

`mongo-express` has [dockerfile here](https://github.com/mongo-express/mongo-express-docker/blob/adc882a30c412639936ee4ac0f3edf22baba37af/Dockerfile), which exposed port 8081

These ports are subsequently exposed in compose file.

As mentioned above, the UD doesn't have the mapped port showing when the workspace is running.

Then I used following command attempt to get the mapped port.
![image](https://cloud.githubusercontent.com/assets/4098537/22185353/dcd18e2a-e098-11e6-8fb7-d422c2af31ca.png)

However I tried to executing the command in different container, but I was only be able to get the mapped port on the container which has dev tools injected.
![image](https://cloud.githubusercontent.com/assets/4098537/22185396/a2574068-e099-11e6-8c16-826ec9fdb778.png)

![image](https://cloud.githubusercontent.com/assets/4098537/22185400/b2214ec6-e099-11e6-8e41-375d57f42646.png)

![image](https://cloud.githubusercontent.com/assets/4098537/22185404/be7cbe58-e099-11e6-951d-ba5aa2be7ef1.png)

So I was not be able to access the mongo-express due to I cannot get the mapped port for 8081 port.

For completeness, here's my workspace config file:
```
{
  "defaultEnv": "wksp-i7y9",
  "environments": {
    "wksp-i7y9": {
      "machines": {
        "mongo": {
          "attributes": {
            "memoryLimitBytes": "1073741824"
          },
          "servers": {},
          "agents": []
        },
        "web": {
          "attributes": {
            "memoryLimitBytes": "1073741824"
          },
          "servers": {},
          "agents": [
            "org.eclipse.che.ws-agent",
            "org.eclipse.che.ssh",
            "org.eclipse.che.terminal"
          ]
        },
        "mongo-admin": {
          "attributes": {
            "memoryLimitBytes": "1073741824"
          },
          "servers": {},
          "agents": []
        }
      },
      "recipe": {
        "type": "compose",
        "content": "services:\n  web:\n    image: eclipse/node\n    expose:\n      - 5000\n  mongo:\n    image: mongo\n  mongo-admin:\n    image: mongo-express\n    expose:\n      - 8081\n",
        "contentType": "application/x-yaml"
      }
    }
  },
  "projects": [],
  "name": "wksp-i7y9",
  "commands": [
    {
      "commandLine": "echo ${server.port.5000}\necho ${server.port.8081}\n",
      "name": " get_port",
      "attributes": {
        "previewUrl": ""
      },
      "type": "custom"
    }
  ],
  "links": []
}
```

Looks like this is a related, but not exactly identical problem as mentioned above.

**Comment by TylerJewell** [comment] 2017-01-22 20:09
@ashumilova - I believe that this gap is urgent enough where we should either a) interrupt the current sprint to investigate a fix for the UD, or b) temporarily remove the commit that removed the ops view from the IDE to restore it, until we have a permanent UD fix.

**Comment by gazarenkov** [comment] 2017-01-23 07:59
@xbtsw 

Meantime you can either (or both)

1/ (as I mentioned earlier it is always recommended) configure the servers you are interesting in, on UD:
Runtime -> Machines -> "mongo-admin" or "web" (in your case) -> Servers -> Add,
define your server reference name (any meaningful word), port (such as 8081 or 5000) and protocol ("http") and then you'll URI on UD servers table just like 

2/ Add "org.eclipse.che.terminal" agent on "mongo-admin" machine and be able to execute command there and see the mapped port  with echo command.

**Comment by gazarenkov** [comment] 2017-01-23 08:02
@ashumilova show address along with URL, unlike URL it always available

**Comment by ashumilova** [comment] 2017-01-23 10:30
We will display address as well, and fix that when protocol is not defined we display - http (which is wrong), and all this info is available in runtime (workspace should be running)

**Comment by slemeur** [comment] 2017-01-23 10:52
Thanks @ashumilova.

Along with those fixes, I propose the following enhancement issue: https://github.com/eclipse/che/issues/3853

**Comment by slemeur** [comment] 2017-01-23 15:49
@xbtsw : Hi Wei, we have the following enhancement issue based on your feedback: eclipse/che#3853. You are very pleased to provide your feedback in the issue.

**Comment by akurinnoy** [comment] 2017-01-24 08:20
Hello @xbtsw, I’m working on a fix for the issue you found. Here is the proposal, if you want to provide some feedbacks, they are welcomed!

https://github.com/eclipse/che/pull/3866

Stevan has already validated, @TylerJewell @gazarenkov  could you check please

**Closed** 2017-03-10 09:06 UTC
Labels: kind/bug, severity/P1, team/plugin
