### ISSUE TITLE
Expose to workspace directory from within the host machine

### ISSUE THREAD

**Issue by wernight** [codenvy/codenvy#1955] opened 2017-03-19 11:58 UTC
**Reproduction Steps:**
This is a blocking issue to mount docker directories from within a workspace.

Like https://github.com/eclipse/che/issues/2771, for Codenvy one may want to trust their users/developers and allow them to build/run docker images from withing a Codenvy workspace (e.g. using the [exposed docker socket](https://github.com/codenvy/codenvy/issues/1925)).

The issue is that volume mounts will not work even if the workspace and docker are on the same machine.

There is a rather simple solution for when docker and the workspace are on the same machine, by at least providing an environment variable with the workspace full path from within the host. For example, from within the workspace it's `/projects` but it may expose like `$CODENVY_WORKSPACE_HOST_DIR` as being `/home//codenvy/instance/data/codenvy/fs/35/9a/34/workspacedl17qxo67sbce4a9`.

Without this information it's pretty much impossible (as far as I know) to mount volumes (i.e. files in the workspace so as to refresh instantly). With such an environment variable, one can create symbolic links, or change mount path and if docker runs on the same machine it'd work.

**Codenvy version:**   5.5.0

**OS and version:**    Linux

**Comment by TylerJewell** [comment] 2017-03-19 17:27
@wernight - your posts make my head hurt in a good way.  I had to reread the older Che threads a couple of times.  

Please help me understand the motivation behind what you are asking.  Your post is jumping into a prescribed implementation approach. However, before we get into possible implementations, I would like to make sure that I agree with the basic end-user workflow that you are envisioning.  Because I suspect that there may be other ways to give your users the flexibility they seek without getting into an infrastructure layer of mapping volume mounts from within the container to the host and back.

@gazarenkov and @garagatyi  will appreciate this conversation.

First, some architectural background.  We view the workspace as a completely virtualized abstraction from the host.  The "projects" and the "state" of the workspace are assets that are isolated and contained within the workspace's runtime.  This isolation and abstraction is helpful because there are different functions we may need to do to the physical infrastructure independent of what is happening within the workspace:
1. A workspace, for example, could be moved from one physical node to another, say for example, during an admin's initiation of a scale-down event to reduce physical nodes.
2. A workspace's projects, which are a set of files contained within the workspace, can be replicated to long term storage. We use rsync for this process and it happens outside of the workspace's lifecycle. Also, this allows us to treat project long term storage as a different class of storage than what is used for say storing workspace configuration, user database, and the so forth (which are codenvy infrastructure items).

Second, as a general architectural direction, we are moving the architecture to support dual deployment of Codenvy on Kubernetes and also stand alone with docker compose using swarm. These two deployment packages are very different, but we largely want the architecture to support both simultaneously in its configuration.  The Kubernetes deployment is particularly complicated because every host, Swarm or Docker dependency (there are nearly 100) that is made within the product has to be refactored into an abstraction layer where we can have different implementations for different environments.  We have been very fortunate that RedHat has started and done a large majority of the work to get Che working as a single node OpenShift service, but now we have about 18 or so additional activities to break the Swarm deployment concepts to allow Codenvy to do the same making use of Red Hat's kubenetes adapter for managing workspaces.  I raise this point because this opens an additional architectural challenge in that if we wnat to support Swarm + Kube at the same time, then there are even further limitations on how a workspace can have access to any kind of host.  Instead, in that scenario, workspaces will have addtional restrictions.

This is not to say that things are impossible, just more layers of complexity to consider.  

So back to your original question, I understand that you may want to allow users to have access to the host at the same time they have access to the workspace, but why? These are generally different class of users and having assumptions between how the 100% abstraction and the host handle file systems could lead to many unintended consequences since plugin developers could start making hard coded assumptions about this reality that creates problems.

Our thinking has been to double down on the concept of the workspace abstraction and ensuring that it offers the full range of development capabilities within that workspace including docker build and run.  However, to do that we see a couple of improvements needed:

1. A workspace's recipe may need to be defined by a Dockerfile or docker compose file which is in a git repository. This means that before a workspace is running, the Codenvy server may need to be able to read the repository to get files out of it.  This would copy certain git functions to also be located in the Codenvy server (today they are only in a workspace's runtime after it starts).  This would allow codenvy in the user dashboard to do certain repo navigation and sourcing.

2. We can additionally do smart things when configuring a new workspace to have it "docker ready".  If we see that the project to be imported into a workspace has a Dockerfile or other aartifacts, we can dynamically inject a docker client, set up DOCKER_HOST (or an appropriate KUBE connection), so that when the end user is within the workspace, they can perform functions like they were on the host.

And then by doing this, the end user feels like a complete host-based solution, but we get to maintain our complete virtual abstraction.

**Comment by wernight** [comment] 2017-03-20 08:25
I've Che working on Kubernetes, I guess you're awake of my GitHub repo for that?

I do get that workspaces may move from machine to machine. What I'm thinking is that it's possible on each machine to have a local docker running and that with a `$CODENVY_WORKSPACE_HOST_DIR` (updated) would allow the use case.

All my projects work now, like Che/Codenvy, on Docker. Basically just running a Docker image generated from source code. Supposing simpler projects, this means just a bunch of `docker build`. More complex ones are like `docker build ... && docker run ... && docker build ...`; you get the idea.

Each of these are a bunch of linked images. So I want to build and run them via for example `docker-compose up`. So far Codenvy/Che could probably do that, but the key is that I mount the source code to the correct location within those images. Here is a simple example:

   nginx:
     build: nginx
     ports:
       - 8080:80
     links:
       - php
     volumes:
        ./www:/srv:ro
   php:
     build: php
     volumes:
        ./www:/srv:ro

This allows:

  - Changing source code (in Codenvy/Che) and reload the page to instantly see results.
  - Changing the `Dockerfile` and rebuilding do test rather rapidly.

If there is a better way to do that I'd be happy to use it and even brag about it.

**Comment by TylerJewell** [comment] 2017-03-20 14:23
If we look just inside of the workspace itself (let's leave off the host concept for a moment), could you have a folder structure that looks like:

```
/projects
/projects/werner
/projects/werner/docker-compose.yml
/projects/werner/www
/projects/werner/www/files
```

And then assuming you had the right access to the host's Docker daemon and the ability to run Docker clients within the workspace, your proposed YAML would be able to run the appropriate files, as it would be volume mounting from the right location.

This presumes a certain folder structure inside the workspace, however.  And so this should logically work, so then I need to understand how this breaks something from your host, please.

**Comment by wernight** [comment] 2017-03-20 14:38
The folder structure is correct. `/projects/werner` being here the content of a project Git cloned repo.

It does not currently work because from within the repo we have `/projects/werner` (structure you gave), but actually docker is running on the host and from the host's perspective this directory is actually located at for example `/home/codenvy/instance/data/codenvy/fs/35/9a/34/workspacedl17qxo67sbce4a9/werner`.

Since this is a seemingly random path, there is no way currently to know this path from within the workspace.

What would work (taking here the simplest hack) is from within the workspace to change `docker-compose.yml` to:

```
nginx:
  build: nginx
  ports:
    - 8080:80
  links:
    - php
  volumes:
     /home/codenvy/instance/data/codenvy/fs/35/9a/34/workspacedl17qxo67sbce4a9/werner/www:/srv:ro
php:
  build: php
  volumes:
     /home/codenvy/instance/data/codenvy/fs/35/9a/34/workspacedl17qxo67sbce4a9/werner/www:/srv:ro
```
Another hack that should work (untested this way) would be:

    $ mkdir -p /home/codenvy/instance/data/codenvy/fs/35/9a/34
    $ ln -s /home/codenvy/instance/data/codenvy/fs/35/9a/34/workspacedl17qxo67sbce4a9 /projects
    $ cd /home/codenvy/instance/data/codenvy/fs/35/9a/34/workspacedl17qxo67sbce4a9
    $ docker-compose up

**Comment by wernight** [comment] 2017-03-21 19:49
This is **the most critical** requirement for me.

I checked workspaces from `docker-compose.yml` but they seems, I'm sorry to say, utterly useless at the moment as they seem to allow no volume mount, no port, and **only a single service**. The point of `docker-compose.yml` is really to have all that.

So to unblock I'd really want to allow exposing the path on the machine Codenvy is running. I do see that it might be seem as exposing some sensitive data so it should be behind a flag. I also see that it may limit vfs and flexibility in having a "virtual" workspace that may not even exist directly accessible on the workspace's machine host. However I see no other short term solution that would allow Codenvy to be useful, that is as more than just a text editor.

**Comment by TylerJewell** [comment] 2017-03-22 05:05
I understand the issue and need time to consider it.  The issue is that if you use a host docker daemon then it's context has to be a host volume.

Host mounting is not the ideal solution however.  I need to think about it a bit more.

**Comment by eivantsov** [comment] 2017-03-22 06:32
@wernight the problem now is that you do not know the path `/home/codenvy/instance/data/codenvy/fs/35/9a/34/`?

**Comment by wernight** [comment] 2017-03-22 07:54
@eivantsov You're right.

Che has, or had, a fixed workspace path (i.e. without seemingly random bits `35/9a/34`). So didn't have that issue.

Codenvy has rsync but at least for me, single machine (the default), the workspace seems to exist also on the disk. I'm not sure that rsync is actually doing anything. May be a remote file system would actually enable that along with speed up workspace startup time by a LOT for larger projects. `nfs` doesn't support `inotify` and it's not encrypted, but `SMB` or `sshfs` should.

**Comment by TylerJewell** [comment] 2017-03-23 05:27
@wernight - I am giving signififcant thought to this, but it will take some time.  Bad luck, but I am heading out on Friday for a 16 day holiday that I have had scheduled for about a year.  It's just something that is important for my wife and I.

But you are correct on the differences between Codenvy and Che.  However, we have frequently considered something like NFS or SMB, but we have always avoided it because they turn out to be solid solutions for read-instensive activities, but less than stellar for write-intensive activities.  We had an implementation that depended upon Gluster or awhile, but the perf was not up to par becuase of write-requirements.  Imagine a scenario where you git clone a repo with 10K small files, the write performance was awful and makes things for end users unusable.

This is generally a characteristic of NFS, SMB or SSHFS.  So as a result, we have spent time thinking about either volume mounts or rsync into the workspace to avoid this limitation.

I am going to think a lot about this on my holiday - but this general use case I believe is very essential to our future.

**Comment by TylerJewell** [comment] 2017-07-05 14:48
Going to close this issue as we are going to work on a formal Che on Kubernetes packaging, which will make use of persistent volumes to handle these scenarios.  Lots of work already being done within RHT on this.  You will want to follow how Che unfolds.

**Closed** 2017-09-05 10:22 UTC
Labels: kind/question
