### ISSUE TITLE
Some factories do not work on the getting-started page

### ISSUE THREAD

**Issue by artaleks9** [codenvy/codenvy#1570] opened 2017-01-20 15:48 UTC
When I create workspaces from template on the 'che getting-started' page, then several of them do not work.

**Reproduction Steps:**
* Got to the - http://www.eclipse.org/che/getting-started/cloud
* Create the workspaces from the list below:
_eXo Task add-on_
_Yeoman Alfresco_
_.NET_
_ASP.NET_

**Expected behavior:**
workspaces should be started.

**Observed behavior:**
workspaces do not start.

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

_eXo Task add-on_
![exo-ad-on](https://cloud.githubusercontent.com/assets/5408906/22155508/5af9b186-df38-11e6-8659-f477c10093db.png)

_Yeoman Alfresco_
![yeoman_alfresco](https://cloud.githubusercontent.com/assets/5408906/22155529/67d9e34e-df38-11e6-8b81-6a8ab9940477.png)

_.NET_
![net-console-app](https://cloud.githubusercontent.com/assets/5408906/22155551/78c5f5b2-df38-11e6-8b93-94abf30d2fd7.png)
 
_ASP.NET_
![asp net-web-app](https://cloud.githubusercontent.com/assets/5408906/22155571/854dbcd4-df38-11e6-9233-2be65f72c3f3.png)

**Comment by riuvshin** [comment] 2017-01-20 15:53
seems that this issue is related to errors which was discovered in logs by @skryzhny 
```
2017-01-19 16:37:57,760[ceSharedPool-13]  [ERROR] [DockerEnvironmentBackupManager 540]  - Error occurred during backup/restore on 'node8.codenvy.io' : Warning: Permanently added '[node8.codenvy.io]:36665,[172.30.12.108]:36665' (ECDSA) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.2]
```

**Comment by riuvshin** [comment] 2017-01-24 16:33
@garagatyi when Im trying to reproduce that issue I got another error "build image not found in out put" do we have open issue for that problem?

**Comment by garagatyi** [comment] 2017-01-25 07:50
I think this issue fits your problem.

**Comment by mkuznyetsov** [comment] 2017-01-26 16:05
Problems with factories:
eXo Task add-on - image has user `exo` which has been created without a password. SSH server refuses to use this user, as it considers it "locked" (he has '!' on his password in /etc/shadow). Hence, rsync fails to connect by SSH. Needs to decide what to do in that case.

ASP.NET - image is based on Debian Wheezy, which supports only old rsync version, that doesn't recognize `--usermap` parameter, hence our rsync script fails. Needs to decide, wheter we support Wheezy, or what to do in the other case.

.NET - same as ASP.NET

Yeoman Alfresco - seems like a bug of Docker: recipe dockerfile is referenced to a raw file from github repository. Upon building (sending build request to docker remote api), Dockerfile suddenly has null-characters `\u0000` appended to the end, which ruin the build. It only happens when size of the Dockerfiles is less than 100 bytes (number of null-chars is `100 - filesize`). Needs to investigate more

**Comment by skabashnyuk** [comment] 2017-01-27 09:50
Yeoman Alfresco  issues related to https://github.com/docker/docker/issues/30500

**Comment by skabashnyuk** [comment] 2017-01-27 10:25
@TylerJewell  Factory 1-3 is this documentation issue?

**Comment by TylerJewell** [comment] 2017-01-27 16:15
Yes, they are definitely some documentation issues.  It's also an issue for @bmicklea to assign to a PM as we should either a) remove these factories from pages, or b) connect with the factory owners (who are with partners) to explore fixes based upon our recommendations.

**Comment by bmicklea** [comment] 2017-01-27 16:46
@mkuznyetsov thanks for the clear analysis. A couple of questions/comments:
- For eXo you say that the user was created without a password, do you mean it was created *with* a password?  I think we need SSH keys with no password, don't we?
- I have now documented that we need a linux distro with rsync that recognizes the `--usermap` parameter so I don't think there's any action here except on us to re-create those factories with a newer OS version

I've already removed those factories from the Che page and reached out to Alfresco owner. I haven't reached out to eXo yet but I will once I know your answer.

**Comment by mkuznyetsov** [comment] 2017-01-31 14:32
@bmicklea 
User 'exo' is being created without password (excerpt from Dockerfile of parent image 'exo-community'):
```
# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
RUN useradd --create-home --user-group --shell /bin/bash ${EXO_USER} && \
    # giving all rights to eXo user
    echo "exo   ALL = NOPASSWD: ALL" > /etc/sudoers.d/exo && chmod 440 /etc/sudoers.d/exo

```

So, this user's entry in /etc/shadow will contain '!' for password. It will mean for Open SSH that user is 'locked' and authentication on that user is disallowed.

**Comment by mkuznyetsov** [comment] 2017-01-31 15:37
Debian Wheezy rsync available version - 3.0.9-4 (https://packages.debian.org/wheezy/net/rsync)
'usermap' attribute is available since 3.1.0 (https://rsync.samba.org/ftp/rsync/src/rsync-3.1.0-NEWS)

**Comment by bmicklea** [comment] 2017-01-31 20:32
Aren't we the owners of .NET and ASP .NET examples?

**Comment by bmicklea** [comment] 2017-01-31 20:42
@mkuznyetsov so how would eXo fix this?

**Comment by bmicklea** [comment] 2017-01-31 21:43
(downgrading to P2 since broken factories have been removed from Che page).

**Comment by mkuznyetsov** [comment] 2017-02-02 09:18
> Aren't we the owners of .NET and ASP .NET examples?
yes, they are based on codenvy/aspnet

> so how would eXo fix this?
User 'exo' must be "not locked" in order to be usable by Open SSH. One wat to do it is by setting predefined/random user password (In our Che and Codenvy images user is created with ones).

**Closed** 2017-02-14 08:12 UTC
Labels: kind/bug, severity/P2, team/platform
