### ISSUE TITLE
Constantly re-reading project structure

### ISSUE THREAD

**Issue by bobpaige** [codenvy/codenvy#1037] opened 2016-10-26 21:44 UTC
With my project (16 submodules and source directories), Codenvy seems to pause every few minutes with a "Reading project structure" status that blocks me from doing anything. I have no background processes modifying/building anything.

Is this normal?

**Reproduction Steps:**

Import project.
Configure source directories.
Navigate around the project.
Watch the fun :)

**Expected behavior:**

I am not surprised to see it load project structure once, or when I change the project classpath, but to have it do this repeatedly is unexpected.

**Observed behavior:**

Reloads project structure multiple times.

**Codenvy version:** 5.0.0-M5
**OS and version:** [Enter OS name and version here]

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: New install
Problem can be reliably reproduced: somewhat random. If I leave it idle it doesn't occur. If I navigate around the project (not modifying anything) it happens more often.

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.

**Comment by TylerJewell** [comment] 2016-10-26 22:20
@dkuleshov - please take a look.

**Comment by tolusha** [comment] 2016-10-27 13:44
Confirmed.

**Comment by bobpaige** [comment] 2016-10-27 14:29
Could it be related to memroy configuration on the workspace? I have 2G RAM allocated.

As part of testing https://github.com/codenvy/codenvy/issues/1036 I imported the ecilpse/che sources into this same workspace and it paused at least a dozen times while it found all the source directories (I declared it as a maven project so it found time automatically).

**Comment by tolusha** [comment] 2016-10-28 06:23
@bobpaige I don't think so.
@TylerJewell I marked the issue as blocker, because I can't do anything.

**Comment by dkuleshov** [comment] 2016-10-28 12:50
Hi, I've did some analysis, as I see it is not likely to be related to server-side and/or filesystem but more likely to the client (IDE) project structure related routines. I want to take a deeper look to get more information, will keep in touch.

**Comment by vparfonov** [comment] 2016-10-28 13:58
Seems like we effectively reproduced the issue, it is related to editor save/auto-save features. Will be fixed in nearest release.

**Closed** 2016-11-08 14:52 UTC
Labels: kind/bug, severity/blocker, team/ide
