### ISSUE TITLE
Meteor preview still don't run

### ISSUE THREAD

**Issue by janat08** [codenvy/codenvy#2212] opened 2017-05-17 17:27 UTC
#2077

http://${server.port.3000} or ${server.3000} won't run.
My old commands with working ports got lost when I reinstalled repos, meanwhile they don't necessarily run depending on which project I pick.

**Comment by janat08** [comment] 2017-05-17 18:15
4403 runs.

**Comment by eivantsov** [comment] 2017-05-18 05:53
@janat08 what do you mean won't run? 3000 is exposed in `eclipse/meteor` image. Please be more specific in your issues otherwise their will either be closed as cannot reproduce or it'll be difficult to help you. Here's a good read - https://github.com/eclipse/che/wiki/Submitting-Bugs-and-Suggestions

**Comment by janat08** [comment] 2017-05-18 11:39
It won't return an actual url to use.

**Comment by janat08** [comment] 2017-05-18 11:40
Doc tells you to use server.port.3000

**Comment by eivantsov** [comment] 2017-05-18 11:50
@janat08 what does it return for you?

**Comment by janat08** [comment] 2017-05-18 17:06
Same as in previous issue: https//${server.3000}

**Comment by eivantsov** [comment] 2017-05-18 17:12
What image do you use?

**Comment by janat08** [comment] 2017-05-18 17:50
meteor.

**Comment by eivantsov** [comment] 2017-05-18 17:53
eclipse/meteor? Sorry, but this isn't possible. Double checked it just now.

**Comment by janat08** [comment] 2017-05-18 23:44
"recipe": {
        "type": "dockerfile",
        "content": "FROM eclipse/meteor\n",
        "contentType": "text/x-dockerfile"
      }
 "commands": [
    {
      "commandLine": "cd ${current.project.path} && meteor --port 4403",
      "name": "newCustom",
      "attributes": {
        "goal": "Run",
        "previewUrl": "http://${server.port.4403}"
      },
      "type": "custom"
    }

**Comment by eivantsov** [comment] 2017-05-19 05:48
@janat08 I am completely lost now. What problem are we trying to solve? What port does your meteor process is bound to? You were talking about port 3000. Now it is port 4403

**Comment by janat08** [comment] 2017-05-19 15:06
Well as I said port 3000 won't work, and 4403 works. It is bound to 4403
after went down macro list for available ports.

**Comment by eivantsov** [comment] 2017-05-19 15:18
> 3000 won't work

I'm afraid it is tool little information for me to be able to help. No additional info, no screenshot, no project. 

Closing as cannot reproduce. Feel free to reopen if you think you can provide any additional details.

**Closed by eivantsov** 2017-05-19 15:18 UTC
Labels: kind/question
