### ISSUE TITLE
Certain Factories are not working since upgrade to 5.0.0-M1

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#779] opened 2016-09-19 17:28 UTC
Since the upgrade to 5.0.0-M1 certain factories are not working anymore. 

The factories identified and not working:
- https://github.com/bitnami/bitnami-docker-express/tree/che
- https://github.com/bitnami/bitnami-docker-swift/tree/che
- https://github.com/bitnami/bitnami-docker-laravel/tree/che
- https://github.com/bitnami/bitnami-docker-symfony/tree/che
- https://github.com/bitnami/bitnami-docker-java-play/tree/che
- https://github.com/bitnami/bitnami-docker-codeigniter/tree/che
- https://github.com/bitnami/bitnami-docker-rails/tree/che

The factories identified hanging:
- vertx: http://beta.codenvy.com/f?id=9skz1321dxbqpj5j
![screen shot 2016-09-19 at 19 22 18](https://cloud.githubusercontent.com/assets/1636769/18641987/371ebc74-7e9f-11e6-8a22-d128227994cd.png)
- Eclipse Che getting started webpage: https://www.eclipse.org/che/getting-started/cloud/

Factories accepted but landing with an error:
- Gitlab: https://beta.codenvy.com/f/?url=https://gitlab.com/benoitf/simple-project.git
![screen shot 2016-09-19 at 19 25 16](https://cloud.githubusercontent.com/assets/1636769/18641903/e11ac674-7e9e-11e6-9783-b2693e63a8b9.png)

**Comment by riuvshin** [comment] 2016-09-19 19:24
all affected factories have codenvy.json with old model whic cause the issue, it could be reproduced on current master.

**Comment by skabashnyuk** [comment] 2016-09-19 22:24
```
2016-09-19 19:04:41,700[spaceManager-98]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 665]    - Start of environment java failed. Error: Error response from docker API, status: 500, message: Error response from daemon: Error downloading remote context http://beta.codenvy.com/api/recipe/recipega4hxep75ipg04yo/script: Got HTTP status code >= 400: 401 Unauthorized

org.eclipse.che.api.core.ServerException: Start of environment java failed. Error: Error response from docker API, status: 500, message: Error response from daemon: Error downloading remote context http://beta.codenvy.com/api/recipe/recipega4hxep75ipg04yo/script: Got HTTP status code >= 400: 401 Unauthorized

	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:277) ~[che-core-api-workspace-5.0.0-M1.jar:5.0.0-M1]
	at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$1(WorkspaceManager.java:649) ~[che-core-api-workspace-5.0.0-M1.jar:5.0.0-M1]
	at org.eclipse.che.api.workspace.server.WorkspaceManager$$Lambda$171/922808511.run(Unknown Source) [che-core-api-workspace-5.0.0-M1.jar:5.0.0-M1]
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-5.0.0-M1.jar:5.0.0-M1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: Error response from daemon: Error downloading remote context http://beta.codenvy.com/api/recipe/recipega4hxep75ipg04yo/script: Got HTTP status code >= 400: 401 Unauthorized

	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:738) ~[che-core-api-workspace-5.0.0-M1.jar:5.0.0-M1]
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:234) ~[che-core-api-workspace-5.0.0-M1.jar:5.0.0-M1]
	at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:246) ~[che-core-api-workspace-5.0.0-M1.jar:5.0.0-M1]
	... 6 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: Error response from daemon: Error downloading remote context http://beta.codenvy.com/api/recipe/recipega4hxep75ipg04yo/script: Got HTTP status code >= 400: 401 Unauthorized

	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:827) ~[che-core-api-workspace-5.0.0-M1.jar:5.0.0-M1]
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:673) ~[che-core-api-workspace-5.0.0-M1.jar:5.0.0-M1]
	... 8 common frames omitted
Caused by: org.eclipse.che.api.core.ServerException: Error response from docker API, status: 500, message: Error response from daemon: Error downloading remote context http://beta.codenvy.com/api/recipe/recipega4hxep75ipg04yo/script: Got HTTP status code >= 400: 401 Unauthorized

	at org.eclipse.che.plugin.docker.machine.ComposeMachineProviderImpl.startService(ComposeMachineProviderImpl.java:335) ~[che-plugin-docker-machine-5.0.0-M1.jar:5.0.0-M1]
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$7(CheEnvironmentEngine.java:663) ~[che-core-api-workspace-5.0.0-M1.jar:5.0.0-M1]
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine$$Lambda$189/2017672467.startMachine(Unknown Source) ~[na:na]
	at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:775) ~[che-core-api-workspace-5.0.0-M1.jar:5.0.0-M1]
	... 9 common frames omitted
```

**Comment by garagatyi** [comment] 2016-09-20 07:29
Factory vertx: http://beta.codenvy.com/f?id=9skz1321dxbqpj5j fails because it contains URL to beta with http instead of https. I merged fix for similar situations where url of recipe matches API endpoint. Since recipe URL from that factory doesn't match API endpoint workaround is not applied to this factory.
#785 has similar problem, but workaround is not designed to fix that situation at all. So we should consider workaround that will make us not send url of dockerfile to docker at all.

**Comment by slemeur** [comment] 2016-09-20 07:57
Not working: All factories on Eclipse Che website - Getting start page: 
https://www.eclipse.org/che/getting-started/cloud/

**Comment by evoevodin** [comment] 2016-09-20 08:57
> The factories identified and not working:

    https://github.com/bitnami/bitnami-docker-express/tree/che
    https://github.com/bitnami/bitnami-docker-swift/tree/che
    https://github.com/bitnami/bitnami-docker-laravel/tree/che
    https://github.com/bitnami/bitnami-docker-symfony/tree/che
    https://github.com/bitnami/bitnami-docker-java-play/tree/che
    https://github.com/bitnami/bitnami-docker-codeigniter/tree/che
    https://github.com/bitnami/bitnami-docker-rails/tree/che

Changes in #787 fix these factories.
BUT, there is a factory https://github.com/bitnami/bitnami-docker-symfony/tree/che
which can't boot workspace due to an error: 
```
[STDERR] /bin/bash: line 114: wget: command not found
```
@tolusha can you please check whether everything is okay with it?

**Comment by riuvshin** [comment] 2016-09-20 13:38
please ignore issue with wget is is only on dev.box where I use wget to hack with free https

**Comment by evoevodin** [comment] 2016-09-20 13:41
Gitlab factory is fixed by [this](https://github.com/codenvy/codenvy/commit/d39f61dd773d4de56afce08a1b4cc5e6fca7ffb5) commit.

All the factories described in the issue work as expected.

**Closed by evoevodin** 2016-09-20 13:41 UTC
Labels: kind/bug, severity/blocker, sprint/current-sprint, status/in-progress, team/platform
