### ISSUE TITLE
Unable to use google component registry

### ISSUE THREAD

**Issue by richtera** [codenvy/codenvy#1879] opened 2017-03-04 02:55 UTC
**Reproduction Steps:**
Try to add us.gcr.io as a registry using an oauth api key
The API key is too long to work.

**Codenvy version:**    
5.0.0-M9

**OS and version:**    
CoreOS
**Docker version:**    

**Codenvy cli.log output:**

**Comment by richtera** [comment] 2017-03-04 02:56
Ref: https://cloud.google.com/container-registry/docs/advanced-authentication
Use auth token.

**Comment by eivantsov** [comment] 2017-03-05 06:36
@richtera adding in user dashboard?  Have you tried to do that in codenvy.env?

**Comment by richtera** [comment] 2017-03-05 12:34
I'll try to add the registry there

**Comment by richtera** [comment] 2017-03-07 15:09
No it ignores it there as well. I added...
```sh
# Docker Private Registry, uncomment to configure
CODENVY_DOCKER_REGISTRY_AUTH_REGISTRY1_URL=us.gcr.io
CODENVY_DOCKER_REGISTRY_AUTH_REGISTRY1_USERNAME=oauth2accesstoken
CODENVY_DOCKER_REGISTRY_AUTH_REGISTRY1_PASSWORD=***********************************************************************************************************************************
```
The registry doesn't show up in the UI and it doesn't work.
Not sure how to proceed.

**Comment by eivantsov** [comment] 2017-03-07 15:28
@richtera it should not show up in the ui.

How do you check if the registry has been added? Custom recipe?

**Comment by richtera** [comment] 2017-03-07 16:07
I tried to create a workspace with one of the images from the registry and just got an error. To be truthful though there was no way to tell what the error was. I looked through the logs and it just said it couldn't get some id. I will do some more analysis if you need

**Comment by richtera** [comment] 2017-03-08 17:35
I created a new stack and changed the source property to point to my registry. I added the registry to the environment. All I get is:
```
2017-03-08 17:32:05,039[aceSharedPool-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 780]    - Docker image build failed. Image id not found in build output.
org.eclipse.che.api.core.ServerException: Docker image build failed. Image id not found in build output.
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:1004) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:810) ~[che-core-api-workspace-5.4.1.jar:5.
4.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:267) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:714) ~[che-core-api-workspace-5.4.1.jar
:5.4.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:106) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:979) [che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:943) [che-core-api-workspace-5.4.1.jar:5.4.1]
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30) ~[che-core-commons-lang-5.4.1.jar:5.4.1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111-internal]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111-internal]
Caused by: org.eclipse.che.api.core.ServerException: Docker image build failed. Image id not found in build output.
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:335) ~[che-plugin-docker-machine-5.4.1.jar:5.4.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$6(CheEnvironmentEngine.java:782) ~[che-core-api-workspace-5.4
.1.jar:5.4.1]
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:946) ~[che-core-api-workspace-5.4.1.jar:5.4.1]
        ... 11 common frames omitted
Caused by: org.eclipse.che.api.machine.server.exception.MachineException: Docker image build failed. Image id not found in build output.
        at com.codenvy.machine.HostedMachineProviderImpl.pullImage(HostedMachineProviderImpl.java:196) ~[codenvy-machine-hosted-5.4.1.jar:5.4.1]
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.prepareImage(MachineProviderImpl.java:379) ~[che-plugin-docker-machine-5.4.1.jar:5.4.1]
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:276) ~[che-plugin-docker-machine-5.4.1.jar:5.4.1]
        ... 13 common frames omitted
Caused by: org.eclipse.che.plugin.docker.client.exception.DockerException: Docker image build failed. Image id not found in build output.
        at org.eclipse.che.plugin.docker.client.DockerConnector.buildImage(DockerConnector.java:829) ~[che-plugin-docker-client-5.4.1.jar:5.4.1]
        at org.eclipse.che.plugin.docker.client.DockerConnector.buildImage(DockerConnector.java:752) ~[che-plugin-docker-client-5.4.1.jar:5.4.1]
        at com.codenvy.swarm.client.SwarmDockerConnector.buildImage(SwarmDockerConnector.java:88) ~[codenvy-machine-hosted-5.4.1.jar:5.4.1]
        at com.codenvy.machine.HostedMachineProviderImpl.pullImage(HostedMachineProviderImpl.java:179) ~[codenvy-machine-hosted-5.4.1.jar:5.4.1]
        ... 15 common frames omitted
```
Unfortunately I can't tell where exactly the error is, but I am assuming it's unable to pull the image.

**Comment by richtera** [comment] 2017-03-08 17:57
Could it be possible that codenvy is trying to parse the docker name?
On gcr the name has to be:
```
us.gcr.io/<projectname>/<dockerbuild>:<dockertag>
```
So there is an additional / in the docker URL.

**Comment by eivantsov** [comment] 2017-03-08 18:37
Can you share workspace agent logs? Yes, it looks like image cannot be pulled.

**Comment by eivantsov** [comment] 2017-03-08 18:38
Can you pull this image using pure Docker and no google cloud cli?

**Comment by richtera** [comment] 2017-03-08 19:06
I can use the normal docker pull:
```
andy@ubuntu:~/selfstudy-jenkins/codenvy$ docker login us.gcr.io
Username (oauth2accesstoken): 
Password: 
Login Succeeded
andy@ubuntu:~/selfstudy-jenkins/codenvy$ docker pull us.gcr.io/<project>/codenvy-node-git-crypt
Using default tag: latest
latest: Pulling from <project>/codenvy-node-git-crypt
Digest: sha256:****
Status: Downloaded newer image for us.gcr.io/<project>/codenvy-node-git-crypt:latest
andy@ubuntu:~/selfstudy-jenkins/codenvy$ 
```

**Comment by richtera** [comment] 2017-03-08 19:38
I am not sure how to get the workspace logs since the workspace never completely starts up.

**Comment by eivantsov** [comment] 2017-03-08 19:42
`/instance/data/logs` - take a look there. There should be a folder `machine` with subfolders named as machine IDs.

**Comment by richtera** [comment] 2017-03-08 19:53
Hmmm not finding that. There is an instance/logs but it contains different things.
I did finally see some interactions on the web page when testing the instance containing:
```
[DOCKER] Pulling repository us.gcr.io/<project>/codenvy-node-git-crypt 
[DOCKER] [ERROR] Error: Status 403 trying to pull repository <project>/codenvy-node-git-crypt: "Unable to access the repository: <project>/codenvy-node-git-crypt; please verify that it exists and you have permission to access it (no valid credential was supplied)."
[ERROR] Docker image build failed. Image id not found in build output.
```
But it seems to indicate to me that the credentials I configured in the environment file are not being used.

**Comment by eivantsov** [comment] 2017-03-08 19:58
Have you restarted Codenvy after editing codenvy.env?

**Comment by richtera** [comment] 2017-03-08 20:18
Yes. Several times actually with various config changes.

**Comment by eivantsov** [comment] 2017-03-10 09:58
Closing the issue as duplicate of https://github.com/codenvy/codenvy/issues/1893

**Closed by eivantsov** 2017-03-10 09:58 UTC
Labels: kind/question
