### ISSUE TITLE
Viewing HTML Files

### ISSUE THREAD

**Issue by bobpaige** [codenvy/codenvy#1060] opened 2016-10-28 17:54 UTC
Is it possible to view HTML files in my workspace from within Codenvy?

**Reproduction Steps:**

When I run our unit test suite from the Gradle commandline, it outputs results in HTML. They are build artifacts so I don't want to push them to git just so I can view them on another machine.

Is there a simple HTML viewer in codenvy?

**Expected behavior:**

Simple HTML viewer that will display HTML files in a workspace, or some way to finagle a URL that displays files for a specific workspace.

**Observed behavior:**

Can only view HTML files from terminal which is very painful :)

**Codenvy version:** 5.0.0-M5
**OS and version:** [Enter OS name and version here]

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: [Yes / No]
Problem can be reliably reproduced: [Yes / No - it's random]

**Diagnostic bundle**
Execute the script on [this page](https://github.com/codenvy/codenvy/wiki/Support-Diagnostics) and post public link to the bundle here.

**Comment by TylerJewell** [comment] 2016-10-28 17:55
Right click on the HTML file.  There is a preview for the file there.

**Comment by bobpaige** [comment] 2016-10-28 18:57
I did not realize that option was there. I even googled for viewing HTML files in Codenvy (honest!)

Tried it, but I get an error:
![image](https://cloud.githubusercontent.com/assets/16456055/19818664/be5ab4f2-9d1e-11e6-8976-b911322b7fba.png)

Is this a configuration issue with our install?

**Comment by TylerJewell** [comment] 2016-10-28 19:00
No, not at all.  That looks like an API refactoring where the IDE client was not updated.  It's interesting becuase HTML preview was only added quietly in M2 or M3.  So very recent - should have been after the API refactoring.  But this looks like a bug that needs to be looked at ASAP.

**Comment by vparfonov** [comment] 2016-11-08 15:19
related issue https://github.com/codenvy/codenvy/issues/1076

**Comment by artaleks9** [comment] 2016-12-22 10:33
Right now this bug is reproduced on the hosted version.

**Comment by riuvshin** [comment] 2017-01-27 09:53
@vparfonov what is the state of that issue? it is planned for 5.2.0 which going tobe released in few days.

**Closed** 2017-01-27 16:00 UTC
Labels: kind/bug, severity/P2, sprint/current-sprint, team/ide

**Comment by mustafa-yilmaz** [comment] 2017-06-25 09:35
It seems that issue (being not able to view ".html" files) keeps its existence, huh?

**Comment by mustafa-yilmaz** [comment] 2017-06-26 15:54
A foot note for newbies (like me): If you can not see the "preview" command on the right-click menu of your "html" file, please be sure that the extension of the file is ".html" , not ".htm" .
