### ISSUE TITLE
Project explorer jumps.

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#1499] opened 2017-01-10 14:51 UTC
When I scroll down the project explorer and try to select a file the project explorer jumps/scrolls to top on the tree menu. This is not happen all the time but does happen often.

![issue](https://cloud.githubusercontent.com/assets/20580888/21810548/e57bd714-d711-11e6-826e-77069ed66717.gif)

**Codenvy version:**    Onprem
Version :5.0.0-SNAPSHOT
Revision :942cc1996e34183e
Build Time :2016-12-28 17:15:27

**OS and version:**    Linode server - Debian
Chrome Version 55.0.2883.87 m (64-bit)

**Comment by TylerJewell** [comment] 2017-01-10 14:52
This is a duplicate of aonther existing issue already reported.  Please consolidate issues and make sure it's reproducible.

**Comment by JamesDrummond** [comment] 2017-01-10 16:12
Didn't see the duplicate. https://github.com/codenvy/codenvy/issues/1488 . I don't know how to reproduce it. It sometimes does not jump to top. I will post my finding on orginal issue.

**Closed** 2017-01-24 03:30 UTC
Labels: kind/bug
