### ISSUE TITLE
Cli codenvy restart command fails when admin's credential is provided

### ISSUE THREAD

**Issue by akorneta** [codenvy/codenvy#1937] opened 2017-03-16 16:32 UTC
**Reproduction Steps:**
- start codenvy
- restart codenvy with credentials

see attachment

**OS and version:**    
```
openSUSE 13.2 (Harlequin) (x86_64)
```

**Docker version:** 
```
Client:
 Version:      17.03.0-ce
 API version:  1.26

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Experimental: false
```

**attachment**
![out-2](https://cloud.githubusercontent.com/assets/12269156/24007264/b8604be6-0a76-11e7-8064-44214f8c085c.gif)

**Comment by riuvshin** [comment] 2017-03-16 16:43
@benoitf you have fixed bug with passing args to `stop` on `restart`, here `stop` is ok, it seems that `start`  somehow received unexpected args

**Comment by benoitf** [comment] 2017-03-16 16:48
the main issue is what args needs to be sent to stop and start when we do "restart"
because some want to give arguments for stop (of restart)
and some want to give arguments for start (of restart)

AFAIK the issue is coming after this change
https://github.com/eclipse/che/commit/dcf6c63683f2431c601bc23bf4a8d5502e14d860#diff-c9d27ea6fa5cef75c1a6559309b947c4

I would say that unknown arguments should be skipped by start instead of reporting the error.

**Comment by riuvshin** [comment] 2017-03-16 16:50
@TylerJewell wdyt?

**Comment by TylerJewell** [comment] 2017-03-16 16:51
I was looking at a bit of the code, and also recognize that there is some other issues with start / restart / stop.  Now, in Che we print out a help message with all of the parameters.  However, the parameters for Che are a subset of those needed for Codenvy.  So if you do `restart --help` it will not display the extra parameters needed for Codenvy such as `--user`.

So I think there should be two fixes:
1. Ignore / skip parameters that are unknown, and:
2. Amend the start / stop / restart help message with an extra variable that allows custom CLI assemblies to add additional parameters to the help message.

**Comment by TylerJewell** [comment] 2017-03-17 13:47
@benoitf - I will assign this to myself.

**Comment by TylerJewell** [comment] 2017-03-18 16:53
Thanks @akorneta for reporting this.  Pull request with a fix - https://github.com/eclipse/che/pull/4475

**Closed** 2017-03-19 17:35 UTC
Labels: kind/bug
